# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm', '0001_squash_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Короткое имя')),
                ('full_name', models.CharField(max_length=80, verbose_name='Полное имя')),
                ('role', models.CharField(choices=[('FOUNDER', 'Основатель'), ('MANAGER', 'Менеджер'), ('VIDEOMANAGER', 'Видеоменеджер'), ('WATCHMAN', 'Админ'), ('TRAINER', 'Тренер'), ('CONSULTANT', 'Внешний консультант'), ('VOLUNTEER', 'Волонтёр')], max_length=20, verbose_name='Должность')),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'нал'), ('ELECTRONIC', 'безнал')], max_length=10, verbose_name='Форма зарплаты')),
                ('vk', models.URLField(blank=True, max_length=255, verbose_name='Профиль VK')),
                ('gender', models.CharField(choices=[('MALE', 'М'), ('FEMALE', 'Ж')], max_length=10, null=True, verbose_name='Пол')),
                ('color', models.CharField(max_length=7)),
                ('cm_login', models.CharField(blank=True, max_length=255, verbose_name='Логин в КМ')),
                ('cm_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_member', to='cm.customer', verbose_name='Клиент в КМ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись на сайте')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'permissions': (('manage', 'Может управлять стаффом и доступами'),),
            },
        ),
        migrations.CreateModel(
            name='AltEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_emails', to='staff.member')),
            ],
        ),
    ]
