# Generated by Django 2.1.5 on 2019-01-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(old_name='MemberAltEmail', new_name='AltEmail',),
    ]
