# Generated by Django 2.1.5 on 2019-01-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_names'),
        ('staff', '0003_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cm_customer',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='cm.Customer',
            ),
        ),
    ]
