# Generated by Django 2.1.5 on 2019-01-15 21:37

from django.db import migrations


def fill_cm_customers(apps, schema_editor):
    Member = apps.get_model('staff', 'Member')
    Customer = apps.get_model('cm', 'Customer')
    for member in Member.objects.all():
        if member.cm_card_id:
            customer = Customer.objects.get(card_id=member.cm_card_id, is_active=True)
            member.cm_customer = customer
            member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_customer_key'),
    ]

    operations = [
        migrations.RunPython(fill_cm_customers),
    ]
