# Generated by Django 2.1.7 on 2019-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20190320_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
    ]
