# Generated by Django 2.2 on 2019-04-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_member_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={
                'permissions': (('manage', 'Может управлять стаффом и доступами'),),
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
