# Generated by Django 3.0.5 on 2020-07-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_pbx_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_current',
        ),
    ]
