# Generated by Django 2.1.7 on 2019-03-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0003_auto_20190329_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem', old_name='watchman', new_name='watchman_name',
        ),
    ]
