# Generated by Django 2.1.7 on 2019-03-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0004_auto_20190330_1151'),
    ]

    operations = [
        migrations.RenameModel(old_name='ScheduleItem', new_name='Shift',),
    ]
