# Generated by Django 2.1.7 on 2019-03-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0006_watchman_fk'),
    ]

    operations = [
        migrations.RemoveField(model_name='shift', name='watchman_name',),
    ]
