# Generated by Django 2.2 on 2019-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0007_drop_old_watchman_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift', name='date', field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(
                choices=[
                    ('MORNING_V1', 'MORNING_V1'),
                    ('EVENING_V1', 'EVENING_V1'),
                    ('MORNING', 'MORNING'),
                    ('MIDDAY', 'MIDDAY'),
                    ('EVENING', 'EVENING'),
                    ('NIGHT', 'NIGHT'),
                ],
                editable=False,
                max_length=20,
            ),
        ),
    ]
