# Generated by Django 2.2 on 2019-08-15 13:39

from django.db import migrations, models
import django.db.models.deletion


def fill_new_watchman(apps, schema_editor):
    Shift = apps.get_model('watchmen', 'Shift')
    Watchman = apps.get_model('watchmen', 'Watchman')

    for shift in Shift.objects.all():
        if shift.watchman_old:
            (watchman, _) = Watchman.objects.get_or_create(member=shift.watchman_old)
            shift.watchman = watchman
            shift.save()


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0009_watchman_fk_p1'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='watchman',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='watchmen.Watchman',
            ),
        ),
        migrations.RunPython(fill_new_watchman),
    ]
