# Generated by Django 2.2 on 2019-08-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0010_watchman_fk_p2'),
    ]

    operations = [
        migrations.RemoveField(model_name='shift', name='watchman_old',),
    ]
