# Generated by Django 2.2.5 on 2019-12-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0014_longer_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
    ]
