# Generated by Django 3.0.5 on 2020-09-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_wagtail', '0006_kochergapage'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('title', models.CharField(editable=False, max_length=255)),
                ('photo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.CustomImage')),
            ],
        ),
    ]
