# Generated by Django 3.0.5 on 2020-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_chat_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
