# Generated by Django 3.0.5 on 2020-09-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_index_active_description'),
        ('telegram', '0005_chat_orderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectPage'),
        ),
    ]
