# Generated by Django 3.1.3 on 2020-12-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_index_active_description'),
        ('telegram', '0006_project_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_chats', 'Can manage all telegram chats')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chats', to='projects.projectpage'),
        ),
    ]
