# Generated by Django 3.1.3 on 2020-12-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='invite_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
