# Generated by Django 3.1.3 on 2020-12-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_chats', 'Can manage all telegram chats'), ('view_all_chats', 'Can list and access all telegram chats'), ('post_to_chats', 'Can post to any telegram chats via bot')]},
        ),
    ]
