# Generated by Django 3.1.3 on 2021-02-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_force_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='delisted',
            field=models.BooleanField(default=False),
        ),
    ]
