apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-mysql-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "10 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: default
            image: {{ .Values.image.mysql_backup | quote }}
            envFrom:
              - secretRef:
                  name: {{ .Release.Name }}-backup
            env:
              - name: DB_HOST
                value: {{ .Release.Name }}-mysql
              - name: DB_NAME
                value: wiki
              - name: DB_USER
                value: wiki
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql
                    key: password
          restartPolicy: OnFailure
