{{ if .Values.domain -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-cert
  dnsNames:
    - {{ .Values.domain | quote }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-notls
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - http
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
      - kind: Service
        name: {{ .Release.Name }}-wiki
        port: 80
    middlewares:
      - name: redirect-https
        namespace: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - https
  tls:
    secretName: {{ .Release.Name }}-cert
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
      - kind: Service
        name: {{ .Release.Name }}-wiki
        port: 80
{{- end }}
