apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-parsoid
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-parsoid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-parsoid
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-parsoid
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-parsoid
    spec:
      enableServiceLinks: false  # Service links collide with Parsoid settings and break it
      containers:
        - name: parsoid
          image: thenets/parsoid:0.10
          ports:
            - containerPort: 8000
          env:
            - name: PARSOID_DOMAIN_wiki
              value: https://{{ required "domain must be set" .Values.domain }}/api.php
