apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
stringData:
  root_password: {{ required "root_password must be set" .Values.database.root_password | quote }}
  password: {{ required "password must be set" .Values.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-settings
  namespace: {{ .Release.Namespace }}
stringData:
  secret-key: {{ required "secret_key must be set" .Values.settings.secret_key | quote }}
  slack-notifications-webhook: {{ .Values.settings.slack_notifications_webhook | quote }}
  google-login-app-id: {{ .Values.settings.google_login.app_id | quote }}
  google-login-secret: {{ .Values.settings.google_login.secret | quote }}
  aws-access-key: {{ required "aws.access_key is required" .Values.settings.aws.access_key | quote }}
  aws-secret-key: {{ required "aws.secret_key is required" .Values.settings.aws.secret_key | quote }}
  aws-bucket-name: {{ required "aws.bucket_name is required" .Values.settings.aws.bucket_name | quote }}
