# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kocherga_wagtail', '0001_squash_2021'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('slides', wagtail.core.fields.StreamField([('slide_title', wagtail.core.blocks.CharBlock(form_classname='title', label='Заголовок')), ('slide_rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'bad', 'embed', 'link', 'h2', 'h3', 'h4', 'hr', 'ol', 'ul', 'image'], label='Текст с разметкой')), ('slide_raw_html', wagtail.core.blocks.RawHTMLBlock(label='Произвольный HTML')), ('slide_fragments', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'bad', 'embed', 'link', 'h2', 'h3', 'h4', 'hr', 'ol', 'ul', 'image'], label='Текст')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(label='Произвольный HTML'))], label='Фрагменты (появляются поочерёдно)'))], blank=True)),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
            bases=('kocherga_wagtail.kochergapage',),
        ),
    ]
