# Generated by Django 3.0.5 on 2020-08-08 22:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('kocherga_wagtail', '0006_kochergapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('slides', wagtail.core.fields.StreamField([('slide_title', wagtail.core.blocks.CharBlock(label='Заголовок')), ('slide_rich_text', wagtail.core.blocks.RichTextBlock(label='Текст с разметкой')), ('slide_raw_html', wagtail.core.blocks.RawHTMLBlock(label='Произвольный HTML'))], blank=True)),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
            bases=('kocherga_wagtail.kochergapage',),
        ),
    ]
