bases:
  - ../base
resources:
  - backend-migrate.yaml
patches:
  - backend-runserver.yaml
  - dev-node.yaml
  - frontend-with-webpack.yaml
secretGenerator:
  - name: kocherga
    envs:
      - secrets/db-passwords.env
    files:
      - secrets/secrets.py
configMapGenerator:
  - name: kocherga
    literals:
      - s3_bucket="kocherga-dev"
    files:
      - configs/main.py
