# Generated by Django 2.2 on 2019-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.TextField(default='', verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
