# Generated by Django 3.0.5 on 2020-06-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_wagtail', '0003_images_data'),
        ('blog', '0004_blogindexpage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostauthor',
            name='image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='kocherga_wagtail.CustomImage',
            ),
        ),
    ]
