image: "berekuk/kocherga-ci"

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .venv/
  - .cache/pip

before_script:
  - poetry install
  - npm config set registry https://npm.team.kocherga.club/
  - echo "//npm.team.kocherga.club/:_authToken=\"$NPM_TOKEN\"" >/root/.npmrc
  - npm config get
  - cat /root/.npmrc
  - npm ci

build:
  stage: build
  script:
    - make front

test:
  stage: test
  script:
    - poetry run make lint
