image: "docker:stable"

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f docker/Dockerfile --build-arg NPM_TOKEN=$NPM_TOKEN -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME make lint

deploy_image:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://$DEPLOY_HOST:2376
    DOCKER_TLS_VERIFY: 1
    TAG: $CI_COMMIT_REF_NAME
    HOST_IP: 172.18.0.1
  script:
    # prepare docker
    - apk add --no-cache py-pip
    - pip install docker-compose
    - mkdir -p ~/.docker
    - echo "$DOCKER_CACERT" > ~/.docker/ca.pem
    - echo "$DOCKER_CERT" > ~/.docker/cert.pem
    - echo "$DOCKER_KEY" > ~/.docker/key.pem
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # migrate
    - docker-compose -c docker/compose.prod.yml run api poetry run ./manage.py migrate
    - docker-compose -c docker/compose.prod.yml run api poetry run ./manage.py collectstatic --no-input
    # deploy
    - docker stack deploy --with-registry-auth -c docker/compose.prod.yml kocherga-core
  only:
    - master
