image: "docker:stable"

before_script:
  ## Setup ssh for deploy.
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t $CI_REGISTRY_IMAGE:latest .
    - "[[ -z $CI_COMMIT_TAG ]] && exit 0"
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG

test:
  stage: test
  script:
    - docker run $CI_REGISTRY_IMAGE:$CI_BUILD_TAG make lint

deploy_js:
  stage: deploy
  script:
    - scp static/dist/*.js kocherga-srv@kocherga.club:/srv/kocherga/core/static/dist/
    - ssh kocherga-srv@kocherga.club 'cd /srv/kocherga/core && . .env && /home/kocherga-srv/.poetry/bin/poetry run ./manage.py collectstatic --no-input'
    - ssh kocherga-srv@kocherga.club 'sudo systemctl restart kocherga-render-server'
  only:
    - master
