image: "berekuk/kocherga-ci"

before_script:
  - pip install poetry
  - poetry config settings.virtualenvs.in-project true
  - poetry install
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}-2
  paths:
  - node_modules/
  - .venv/

build:
  stage: build
  script:
    - make front

test:
  stage: test
  script:
    - poetry run make lint
