image: "python:3.7"

before_script:
  - pip install poetry
  - poetry config settings.virtualenvs.in-project true
  - poetry install
  - npm ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .venv/

build:
  stage: build
  script:
    - echo ok

test:
  stage: test
  script:
    - poetry run make lint
