# Workaround for codecov-python - see https://github.com/codecov/codecov-python/issues/96
# Still unpatched as of 2019-06.
variables:
  pass_env: "-e CODECOV_TOKEN -e CI_BUILD_ID=$CI_JOB_ID -e CI_BUILD_REF_NAME=$CI_COMMIT_REF_NAME -e CI_BUILD_ID=$CI_JOB_ID -e CI_REPOSITORY_URL -e CI_BUILD_REF=$CI_COMMIT_SHA -e CI_SERVER_NAME -e CI_PROJECT_DIR=/code"

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-backend:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - docker build -f backend/Dockerfile --build-arg NPM_TOKEN=$NPM_TOKEN -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME

build-frontend:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - docker build -f frontend/Dockerfile --build-arg NPM_TOKEN=$NPM_TOKEN -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME ./frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME

build-chrome:
  stage: build
  script:
    - docker build -f docker/Dockerfile.chrome -t $CI_REGISTRY_IMAGE/chrome:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE/chrome:$CI_COMMIT_REF_NAME

test-lint:
  stage: test
  variables:
    TAG: $CI_COMMIT_REF_NAME
  script:
    - docker-compose -f docker/compose.ci.yml run --rm api flake8 kocherga/ --max-line-length=120

test-js:
  stage: test
  variables:
    TAG: $CI_COMMIT_REF_NAME
  script:
    - docker-compose -f docker/compose.ci.yml run --rm render-server bash -c "cd jsx && npx tsc"
    - docker-compose -f docker/compose.ci.yml run $pass_env
      --rm render-server
      bash -c "
        npx jest --no-watchman --coverage
        && ls -l
        && codecov -F js
      "

test-python:
  stage: test
  variables:
    TAG: $CI_COMMIT_REF_NAME
  script:
    - mkdir -p data/upload/mailchimp data/upload/assets data/upload/fonts data/upload/images
    - docker-compose -f docker/compose.ci.yml run $pass_env
      --rm api
      bash -c "
        pytest -m 'not google and not slack and not mailchimp and not ofd and not vk and not timepad and not slow' --cov=kocherga
        && codecov -F python
      "

deploy-stack:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://$DEPLOY_HOST:2376
    DOCKER_TLS_VERIFY: 1
    TAG: $CI_COMMIT_REF_NAME
    HOST_IP: $DEPLOY_HOST
  script:
    # prepare docker
    - mkdir -p ~/.docker
    - echo "$DOCKER_CACERT" > ~/.docker/ca.pem
    - echo "$DOCKER_CERT" > ~/.docker/cert.pem
    - echo "$DOCKER_KEY" > ~/.docker/key.pem
    # one more login, since we changed the docker endpoint
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # migrate and collect static
    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    - docker pull $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    - docker pull $CI_REGISTRY_IMAGE/chrome:$CI_COMMIT_REF_NAME
    - docker-compose -f docker/compose.prod.yml run --rm api ./scripts/upgrade.sh
    # deploy
    - docker-compose -f docker/compose.prod.yml up -d
  only:
    - master
