version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - /data/kocherga-db:/var/lib/mysql
      - ./mysql.conf.d:/etc/mysql/conf.d

  api:
    image: registry.gitlab.com/kocherga/code/core
    ports:
      - "8000:80"
    volumes:
      - /data/kocherga:/data
    depends_on:
      - db
      - render-server

  render-server:
    image: registry.gitlab.com/kocherga/code/core
    command: /usr/bin/node ./static/dist/render-server.js

  tgbot:
    image: registry.gitlab.com/kocherga/code/core
    command: poetry run ./scripts/tgbot.py
    volumes:
      - /data/kocherga:/data
    # TODO - expose RPC port
    depends_on:
      - db

  ludwig:
    image: registry.gitlab.com/kocherga/code/core
    command: poetry run ./scripts/ludwig.py
    volumes:
      - /data/kocherga:/data
    ports:
      - "5200:80"
    depends_on:
      - db

  worker:
    image: registry.gitlab.com/kocherga/code/core
    command: poetry run ./scripts/worker.py
    volumes:
      - /data/kocherga:/data
    depends_on:
      - db

  importer:
    image: registry.gitlab.com/kocherga/code/core
    command: poetry run ./scripts/importer.py
    volumes:
      - /data/kocherga:/data
    depends_on:
      - db
