version: '3'

services:
  api:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: poetry run gunicorn -w 4 -t 180 -b 0.0.0.0:80 kocherga.django.wsgi
    ports:
      - "5300:80"
    extra_hosts:
      - "db:172.20.0.1"
    volumes:
      - /data/kocherga:/data
      - /config/tier.txt:/code/tier.txt
      - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py
    depends_on:
      - render-server

  render-server:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: /usr/bin/node ./static/dist/render-server.js

  tgbot:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: poetry run ./scripts/tgbot.py
    extra_hosts:
      - "db:172.20.0.1"
    volumes:
      - /data/kocherga:/data
      - /config/tier.txt:/code/tier.txt
      - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py

  ludwig:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: poetry run ./scripts/ludwig.py
    ports:
      - "5200:80"
    extra_hosts:
      - "db:172.20.0.1"
    volumes:
      - /config/tier.txt:/code/tier.txt
      - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py

  importer:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: poetry run ./scripts/importer.py
    extra_hosts:
      - "db:172.20.0.1"
    volumes:
      - /data/kocherga:/data
      - /config/tier.txt:/code/tier.txt
      - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py

  worker:
    image: registry.gitlab.com/kocherga/code/core:${TAG}
    command: poetry run ./scripts/worker.py
    extra_hosts:
      - "db:172.20.0.1"
    volumes:
      - /data/kocherga:/data
      - /config/tier.txt:/code/tier.txt
      - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py
