apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/backend
    context: backend
    sync:
      infer:
      - kocherga/**
      - test/**
    kaniko:
      # TODO - resource limits
      # TODO - enable kaniko optionally in profile, to allow local builds (which can be faster)
      cache: {}
  - image: registry.gitlab.com/kocherga/core/frontend
    context: frontend
    sync:
      infer:
      - src/**
      - server/**
    kaniko:
      cache: {}
  - image: registry.gitlab.com/kocherga/core/chrome
    context: chrome
    kaniko:
      cache: {}
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  cluster:
    dockerConfig:
      path: ./docker.json  # TODO - move to using `secretName` instead and store docker config in k8s cluster

portForward:
- resourceType: deployment
  resourceName: kocherga-frontend
  port: 80
  localPort: 8000

profiles:
- name: dev
  activation:
    - command: dev
  deploy:
    kubeContext: dev
    kustomize:
      paths:
      - k8s/dev
- name: prod
  activation:
    - command: run
  deploy:
    kubeContext: prod
    kustomize:
      paths:
      - k8s/prod
