apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/backend
    context: backend
    sync:
      infer:
      - scripts/**
      - kocherga/**
      - tests/**
  - image: registry.gitlab.com/kocherga/core/frontend
    context: frontend
    sync:
      infer:
      - src/**
      - server/**
  - image: registry.gitlab.com/kocherga/core/chrome
    context: ops/images/chrome
  - image: registry.gitlab.com/kocherga/core/mysql-backup
    context: ops/images/mysql-backup
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha

portForward:
- resourceType: service
  resourceName: kocherga-frontend
  port: 80
  localPort: 8000
- resourceType: service
  resourceName: kocherga-backend
  port: 80
  localPort: 8001

profiles:
- name: dev
  activation:
    - command: dev
  deploy:
    kubeContext: dev
    kustomize:
      paths:
      - ops/k8s/dev
- name: prod
  activation:
    - command: run
  deploy:
    kubeContext: prod
    kustomize:
      paths:
      - ops/k8s/prod
