apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/backend
    context: backend
    sync:
      infer:
      - kocherga/**
      - test/**
    kaniko:
      cache: {}
  - image: registry.gitlab.com/kocherga/core/frontend
    context: frontend
    sync:
      infer:
      - src/**
      - server/**
    kaniko:
      cache: {}
  - image: registry.gitlab.com/kocherga/core/chrome
    context: chrome
    kaniko:
      cache: {}
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  cluster:
    dockerConfig:
      path: ./docker.json
deploy:
  kustomize:
    paths:
    - k8s/dev
portForward:
- resourceType: deployment
  resourceName: kocherga-frontend
  port: 80
  localPort: 8000
