apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/kocherga/core/backend
      context: backend
      sync:
        manual:
          - src: scripts/**
            dest: .
          - src: kocherga/**
            dest: .
          - src: tests/**
            dest: .
        # infer:
        #   - scripts/**
        #   - kocherga/**
        #   - tests/**
    - image: registry.gitlab.com/kocherga/core/frontend
      context: frontend
      sync:
        # frontend Dockerfile is multi-stage and skaffold can't figure out infer syncs, so we use manual instead
        manual:
          - src: src/**
            dest: .
          - src: server/**
            dest: .
          - src: public/**
            dest: .
    - image: registry.gitlab.com/kocherga/core/booking
      context: booking
    - image: registry.gitlab.com/kocherga/core/chrome
      context: ops/images/chrome
    - image: registry.gitlab.com/kocherga/core/mysql-backup
      context: ops/images/mysql-backup
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
portForward:
  - resourceType: service
    resourceName: core-frontend
    port: 80
    localPort: 8000
  - resourceType: service
    resourceName: core-backend
    port: 80
    localPort: 8001
profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /build/artifacts/1/docker
        value:
          target: base # avoid slow `next build`
    build:
      local:
        push: false
    deploy:
      helm:
        releases:
          - name: core
            chartPath: ops/charts/core
            valuesFiles:
              - ops/values/core/dev/main.yaml
              - ops/secrets/core/dev/main.yaml
            artifactOverrides:
              image.backend: registry.gitlab.com/kocherga/core/backend
              image.booking: registry.gitlab.com/kocherga/core/booking
              image.chrome: registry.gitlab.com/kocherga/core/chrome
              image.frontend: registry.gitlab.com/kocherga/core/frontend
              image.mysql_backup: registry.gitlab.com/kocherga/core/mysql-backup
            setFiles:
              config.main_py: ops/values/core/dev/main.py
              config.secrets_py: ops/secrets/core/dev/secrets.py
        flags:
          upgrade:
            - --install
      statusCheckDeadlineSeconds: 600
      kubeContext: dev
  - name: prod
    activation:
      - command: run
      - command: deploy
    deploy:
      helm:
        releases:
          - name: core
            chartPath: ops/charts/core
            valuesFiles:
              - ops/values/core/prod/main.yaml
              - ops/secrets/core/prod/main.yaml
            artifactOverrides:
              image.backend: registry.gitlab.com/kocherga/core/backend
              image.booking: registry.gitlab.com/kocherga/core/booking
              image.chrome: registry.gitlab.com/kocherga/core/chrome
              image.frontend: registry.gitlab.com/kocherga/core/frontend
              image.mysql_backup: registry.gitlab.com/kocherga/core/mysql-backup
            setFiles:
              config.KKMServer_pem: ops/secrets/core/prod/KKMServer.pem
              config.main_py: ops/values/core/prod/main.py
              config.secrets_py: ops/secrets/core/prod/secrets.py
        flags:
          upgrade:
            - --install
      statusCheckDeadlineSeconds: 600
      kubeContext: prod
