apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/backend
    context: backend
    kaniko:
      cache: {}
    sync:
      infer:
        - kocherga/**
        - test/**
  - image: registry.gitlab.com/kocherga/core/frontend
    context: frontend
    kaniko:
      cache: {}
    sync:
      infer:
        - src/**
        - server/**
  - image: registry.gitlab.com/kocherga/core/chrome
    context: chrome
    kaniko:
      cache: {}
  cluster:
    dockerConfig:
      path: ./docker.json
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
portForward:
  - resourceType: deployment
    resourceName: kocherga-frontend
    port: 80
    localPort: 8000
deploy:
  kustomize:
    path: k8s/dev
