apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/backend
    context: backend
    sync:
      infer:
      - kocherga/**
      - test/**
  - image: registry.gitlab.com/kocherga/core/frontend
    context: frontend
    sync:
      infer:
      - src/**
      - server/**
  - image: registry.gitlab.com/kocherga/core/chrome
    context: chrome
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha

portForward:
- resourceType: deployment
  resourceName: kocherga-frontend
  port: 80
  localPort: 8000

profiles:
- name: dev
  activation:
    - command: dev
  deploy:
    kubeContext: dev
    kustomize:
      paths:
      - k8s/dev
- name: prod
  activation:
    - command: run
  deploy:
    kubeContext: prod
    kustomize:
      paths:
      - k8s/prod
