# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=1024)),
            ],
            options={
                'permissions': (('marketing', 'Может контролировать ФБ-маркетинг'),),
            },
        ),
    ]
