# Generated by Django 2.1.7 on 2019-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=1024)),
            ],
        ),
    ]
