# Generated by Django 2.2 on 2019-08-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={
                'permissions': (('marketing', 'Может контролировать ФБ-маркетинг'),)
            },
        ),
    ]
