# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tochka_auth',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ts', models.IntegerField()),
                ('purpose', models.TextField()),
                ('document_type', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counterparty_name', models.CharField(blank=True, max_length=1024)),
                ('counterparty_inn', models.CharField(blank=True, max_length=20)),
                ('counterparty_bank_bic', models.CharField(blank=True, max_length=20)),
                ('counterparty_bank_account_number', models.CharField(blank=True, max_length=40)),
                ('counterparty_bank_name', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'db_table': 'tochka_records',
            },
        ),
    ]
