# Generated by Django 2.1.7 on 2019-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tochka', '0003_auto_20190227_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth', name='dt', field=models.DateTimeField(auto_now=True),
        ),
    ]
