# Generated by Django 3.0.5 on 2020-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_wagtail', '0003_images_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
