# Generated by Django 3.0.5 on 2020-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_wagtail', '0004_private_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
