# Generated by Django 3.0.5 on 2020-08-08 22:05

from django.db import migrations
import kocherga.wagtail.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('kocherga_wagtail', '0005_public_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='KochergaPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(kocherga.wagtail.mixins.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
