version: "3.4"

services:
  core-mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: kocherga
      MYSQL_USER: kocherga
      MYSQL_PASSWORD: "test"
    volumes:
      - ./mysql.conf.d:/etc/mysql/conf.d

  core-redis:
    image: redis:5.0

  core-chrome:
    image: ${CHROME_IMAGE}
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:9222:9222"
    privileged: true

  core-django:
    image: ${BACKEND_IMAGE}
    volumes:
      - ./ci.py:/code/kocherga/django/settings/main.py
      - ./ci_secrets.py:/code/kocherga/django/settings/ci_secrets.py
    environment:
      DB_HOST: "core-mysql"
      DB_PASSWORD: "test"
      REDIS_HOST: "core-redis"
      KOCHERGA_WEBSITE: "http://localhost:8000"
    depends_on:
      - core-mysql
      - core-redis
      - core-chrome
