version: '3.4'

services:
  kocherga-mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: kocherga
      MYSQL_USER: kocherga
      MYSQL_PASSWORD: "test"
    volumes:
      - ./mysql.conf.d:/etc/mysql/conf.d

  kocherga-redis:
    image: redis:5.0

  kocherga-chrome:
    image: ${CHROME_IMAGE}
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:9222:9222"
    privileged: true

  kocherga-backend:
    image: ${BACKEND_IMAGE}
    volumes:
      - ./ci.py:/code/kocherga/django/settings/main.py
      - ./ci_secrets.py:/code/kocherga/django/settings/ci_secrets.py
    environment:
      DB_PASSWORD: "test"
    depends_on:
      - kocherga-mysql
      - kocherga-redis
      - kocherga-chrome
