# Generated by Django 2.1.7 on 2019-03-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20190320_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='paid_dt',
            new_name='redeem_dt',
        ),
    ]
