# Generated by Django 2.1.5 on 2019-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('created_ts', models.IntegerField()),
                ('updated_ts', models.IntegerField()),
            ],
            options={
                'db_table': 'gitlab_issues',
            },
        ),
        migrations.CreateModel(
            name='IssueNote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('created_ts', models.IntegerField()),
                ('updated_ts', models.IntegerField()),
            ],
            options={
                'db_table': 'gitlab_issue_notes',
            },
        ),
    ]
