# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('kkmserver', 'Can access kkmserver'), ('ofd', 'Can access imported OFD data')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_shift_closed', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего закрытия смены')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfdDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electronic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_type', models.CharField(choices=[('income', 'income'), ('refund_income', 'refund_income'), ('expense', 'expense'), ('refund_expense', 'refund_expense')], max_length=40)),
                ('shift_id', models.IntegerField()),
                ('request_id', models.IntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('operator_inn', models.BigIntegerField(null=True)),
                ('fiscal_sign', models.BigIntegerField()),
                ('midday_ts', models.IntegerField()),
                ('document_id', models.IntegerField()),
                ('imported_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OfdFiscalDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_drive_number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfdDocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.IntegerField()),
                ('payment_type', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kkm.ofddocument')),
            ],
        ),
        migrations.AddField(
            model_name='ofddocument',
            name='fiscal_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='kkm.ofdfiscaldrive'),
        ),
        migrations.CreateModel(
            name='OfdShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('electronic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_dt', models.DateTimeField(blank=True, null=True)),
                ('open_dt', models.DateTimeField()),
                ('imported_json', models.JSONField()),
                ('fiscal_drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='kkm.ofdfiscaldrive')),
            ],
            options={
                'ordering': ['-open_dt'],
                'unique_together': {('fiscal_drive', 'shift_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ofddocument',
            unique_together={('document_id', 'fiscal_drive')},
        ),
    ]
