# Generated by Django 3.0.10 on 2020-11-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('kkmserver', 'Access to kkmserver calls')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
