# Generated by Django 3.0.10 on 2020-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0002_kkmserver_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfdKkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_drive_number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
    ]
