# Generated by Django 3.0.10 on 2020-11-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0003_ofd_kkt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('kkmserver', 'Can access kkmserver')]},
        ),
        migrations.AddField(
            model_name='ofddocument',
            name='kkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='kkm.OfdKkt'),
        ),
    ]
