# Generated by Django 3.1.3 on 2020-11-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0006_ofd_items_and_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofddocument',
            name='fiscal_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='kkm.ofdfiscaldrive'),
        ),
    ]
