# Generated by Django 3.1.3 on 2020-11-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0007_fiscal_drive_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfdShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('electronic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_dt', models.DateTimeField(blank=True, null=True)),
                ('open_dt', models.DateTimeField()),
                ('imported_json', models.JSONField()),
                ('fiscal_drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='kkm.ofdfiscaldrive')),
            ],
            options={
                'unique_together': {('fiscal_drive', 'shift_id')},
            },
        ),
    ]
