# Generated by Django 3.1.3 on 2020-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0008_ofd_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofdshift',
            options={'ordering': ['-open_dt']},
        ),
        migrations.AddField(
            model_name='ofddocument',
            name='document_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ofddocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ofddocument',
            unique_together={('document_id', 'fiscal_drive')},
        ),
    ]
