# Generated by Django 3.1.3 on 2020-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0010_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='last_shift_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего закрытия смены'),
        ),
    ]
