# Generated by Django 2.1.7 on 2019-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tochka', '0002_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
