# Generated by Django 2.2.5 on 2019-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tochka', '0004_auth_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='counterparty_bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='record',
            name='counterparty_bank_bic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='counterparty_bank_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='record',
            name='counterparty_inn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
