# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=40)),
                ('watchman', models.CharField(max_length=100)),
                ('cash_income', models.IntegerField(null=True)),
                ('electronic_income', models.IntegerField(null=True)),
                ('total_income', models.IntegerField(null=True)),
                ('current_cash', models.IntegerField(null=True)),
                ('notes', models.TextField()),
                ('discrepancy', models.IntegerField(null=True)),
                ('spendings', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'cashier',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('redeem_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_dt'],
                'permissions': (('create', 'Может выписывать новые чеки'), ('redeem', 'Может обналичивать существующие чеки')),
            },
        ),
    ]
