# Generated by Django 2.1.5 on 2019-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CashierItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('shift', models.CharField(max_length=40)),
                ('watchman', models.CharField(max_length=100)),
                ('cash_income', models.IntegerField(null=True)),
                ('electronic_income', models.IntegerField(null=True)),
                ('total_income', models.IntegerField(null=True)),
                ('current_cash', models.IntegerField(null=True)),
                ('notes', models.TextField()),
                ('discrepancy', models.IntegerField(null=True)),
                ('spendings', models.IntegerField(null=True)),
            ],
            options={'db_table': 'cashier',},
        ),
        migrations.AlterUniqueTogether(
            name='cashieritem', unique_together={('date', 'shift')},
        ),
    ]
