# Generated by Django 2.1.7 on 2019-03-19 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='whom',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cheques',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
