# Generated by Django 2.1.7 on 2019-03-20 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_auto_20190320_0232'),
    ]

    operations = [
        migrations.RemoveField(model_name='cheque', name='cashed_date',),
        migrations.RemoveField(model_name='cheque', name='dt',),
        migrations.AddField(
            model_name='cheque',
            name='created_dt',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Дата создания',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='paid_dt',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дата получения'
            ),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='whom',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cheques',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кому',
            ),
        ),
    ]
