# Generated by Django 2.2 on 2019-07-06 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashier', '0009_redeem_permission'),
    ]

    operations = [
        migrations.RenameModel(old_name='Cheque', new_name='Payment',),
    ]
