# Generated by Django 3.0.10 on 2020-11-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_index_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_dt'], 'permissions': (('create', 'Может выписывать новые чеки'), ('redeem', 'Может обналичивать существующие чеки')), 'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
    ]
