bases:
  - ../base
resources:
  - ingress.yaml
secretGenerator:
  - name: kocherga
    envs:
      - secrets/db-passwords.env
    files:
      - secrets/secrets.py
configMapGenerator:
  - name: kocherga
    literals:
      - s3_bucket="kocherga"
    files:
      - configs/main.py
