bases:
  - ../base
secretGenerator:
  - name: kocherga
    envs:
      - secrets/db-passwords.env
    files:
      - secrets/secrets.py
configMapGenerator:
  - name: kocherga
    files:
      - configs/main.py
