# Generated by Django 2.2 on 2019-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190519_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
