# Generated by Django 2.2 on 2019-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpage_acitivity_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='acitivity_summary',
            new_name='activity_summary',
        ),
    ]
