# Generated by Django 2.1.5 on 2019-02-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0004_auto_20190207_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='training',
            name='gdrive_link',
            field=models.URLField(blank=True, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='training',
            name='post_survey_link',
            field=models.URLField(blank=True, verbose_name='Форма пострассылки'),
        ),
        migrations.AddField(
            model_name='training',
            name='pre_survey_link',
            field=models.URLField(blank=True, verbose_name='Форма предрассылки'),
        ),
        migrations.AddField(
            model_name='training',
            name='telegram_link',
            field=models.URLField(blank=True, verbose_name='Телеграм-чат'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ratio.Training', verbose_name='Тренинг'),
        ),
    ]
