# Generated by Django 2.1.5 on 2019-02-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0010_auto_20190208_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('section', 'Cекция'),
                    ('break', 'Перерыв'),
                    ('bonus', 'Бонус'),
                ],
                default='section',
                max_length=40,
                verbose_name='Тип',
            ),
            preserve_default=False,
        ),
    ]
