# Generated by Django 2.1.5 on 2019-02-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0013_auto_20190208_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trainer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='ratio.Trainer',
                verbose_name='Ведущий',
            ),
        ),
    ]
