# Generated by Django 2.1.5 on 2019-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0014_auto_20190208_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity', options={'ordering': ('day', 'time')},
        ),
        migrations.AddField(
            model_name='trainer',
            name='short_name',
            field=models.CharField(
                default='кто-то', max_length=40, verbose_name='Короткое имя'
            ),
            preserve_default=False,
        ),
    ]
