# Generated by Django 2.2 on 2019-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0018_training_salaries_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
