# Generated by Django 2.2 on 2019-05-04 15:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('ratio', '0021_auto_20190502_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIndexPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'body',
                    wagtail.core.fields.StreamField(
                        [
                            ('ratio_briefing', wagtail.core.blocks.CharBlock()),
                            ('ratio_header', wagtail.core.blocks.CharBlock()),
                            ('ratio_paragraph', wagtail.core.blocks.RichTextBlock()),
                            ('ratio_inset', wagtail.core.blocks.RichTextBlock()),
                            (
                                'ratio_exercise',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('header', wagtail.core.blocks.CharBlock()),
                                        (
                                            'lines_count',
                                            wagtail.core.blocks.IntegerBlock(),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
    ]
