# Generated by Django 2.2 on 2019-05-04 17:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0022_sectionindexpage_sectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField(
                [
                    ('ratio_briefing', wagtail.core.blocks.RichTextBlock()),
                    (
                        'ratio_header',
                        wagtail.core.blocks.CharBlock(classname='full title'),
                    ),
                    ('ratio_paragraph', wagtail.core.blocks.RichTextBlock()),
                    ('ratio_inset', wagtail.core.blocks.RichTextBlock()),
                    (
                        'ratio_exercise',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('header', wagtail.core.blocks.CharBlock()),
                                ('lines_count', wagtail.core.blocks.IntegerBlock()),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
