# Generated by Django 2.2 on 2019-05-05 21:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('ratio', '0023_auto_20190504_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookIndexPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NotebookPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'sections',
                    modelcluster.fields.ParentalManyToManyField(
                        related_name='_notebookpage_sections_+', to='ratio.SectionPage'
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
    ]
