# Generated by Django 2.2 on 2019-05-05 21:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0024_notebookindexpage_notebookpage'),
    ]

    operations = [
        migrations.RemoveField(model_name='notebookpage', name='sections',),
        migrations.AddField(
            model_name='notebookpage',
            name='sections',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'ratio_notebook_section',
                        wagtail.core.blocks.PageChooserBlock(
                            page_type=['ratio.SectionPage']
                        ),
                    )
                ],
                default={},
            ),
            preserve_default=False,
        ),
    ]
