# Generated by Django 2.2 on 2019-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0029_auto_20190508_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локация'),
        ),
    ]
