# Generated by Django 2.2 on 2019-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0030_auto_20190508_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='long_name',
            field=models.CharField(
                default='', max_length=255, verbose_name='Длинное имя'
            ),
            preserve_default=False,
        ),
    ]
