# Generated by Django 2.2 on 2019-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0032_ticket_fiscalization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
