# Generated by Django 2.2 on 2019-07-11 20:52

from django.db import migrations, models


def fill_slugs(apps, schema_editor):
    Activity = apps.get_model('ratio', 'Activity')
    Ticket = apps.get_model('ratio', 'Ticket')

    for model_class in (Activity, Ticket):
        for obj in model_class.objects.all():
            obj.training_slug = obj.training.slug
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0033_unique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='training_slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='training_slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(fill_slugs),
    ]
