# Generated by Django 2.2 on 2019-07-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0034_training_pk_p1'),
    ]

    operations = [
        migrations.RemoveField(model_name='activity', name='training',),
        migrations.AlterUniqueTogether(
            name='ticket', unique_together={('training_slug', 'email')},
        ),
        migrations.RemoveField(model_name='ticket', name='training',),
    ]
