# Generated by Django 2.2 on 2019-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0035_training_pk_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training', name='name', field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='training',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
            preserve_default=False,
        ),
    ]
