# Generated by Django 2.2 on 2019-07-11 21:03

from django.db import migrations, models
import django.db.models.deletion


def fill_fk(apps, schema_editor):
    Activity = apps.get_model('ratio', 'Activity')
    Ticket = apps.get_model('ratio', 'Ticket')
    Training = apps.get_model('ratio', 'Training')

    for model_class in (Activity, Ticket):
        for obj in model_class.objects.all():
            training = Training.objects.get(slug=obj.training_slug)
            obj.training = training
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0036_training_pk_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='training',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedule',
                to='ratio.Training',
                verbose_name='Тренинг',
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='training',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='ratio.Training',
                verbose_name='Тренинг',
            ),
        ),
        migrations.RunPython(fill_fk),
    ]
