# Generated by Django 2.2 on 2019-07-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0037_training_pk_p4'),
    ]

    operations = [
        migrations.RemoveField(model_name='activity', name='training_slug',),
        migrations.AlterField(
            model_name='activity',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedule',
                to='ratio.Training',
                verbose_name='Тренинг',
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='ratio.Training',
                verbose_name='Тренинг',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='ticket', unique_together={('training', 'email')},
        ),
        migrations.RemoveField(model_name='ticket', name='training_slug',),
    ]
