# Generated by Django 2.2 on 2019-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0038_training_pk_p5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_type',
            field=models.CharField(
                choices=[
                    ('none', '-'),
                    ('timepad', 'Timepad'),
                    ('website', 'Сайт'),
                    ('crowdfunding', 'Краудфандинг'),
                    ('cash', 'Нал'),
                    ('invoice', 'Счёт'),
                    ('transfer', 'Перевод'),
                ],
                default='website',
                max_length=40,
                verbose_name='Вид оплаты',
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(
                choices=[
                    ('normal', 'Обычный'),
                    ('stipend', 'Стипендия'),
                    ('staff', 'Стафф'),
                    ('replacement', 'Замена (заменяет другого участника)'),
                    ('carry-over', 'Перенос (с прошлого мероприятия)'),
                ],
                default='normal',
                max_length=40,
                verbose_name='Тип билета',
            ),
        ),
    ]
