# Generated by Django 2.2.5 on 2019-11-15 22:30

from django.db import migrations, models
import django.db.models.deletion

from datetime import timedelta


def fill_training_day(apps, schema_editor):
    Activity = apps.get_model('ratio', 'Activity')
    TrainingDay = apps.get_model('ratio', 'TrainingDay')

    for activity in Activity.objects.all():
        first_date = activity.training.date
        date = first_date + timedelta(days=activity.day - 1)

        (day, _) = TrainingDay.objects.get_or_create(
            training=activity.training,
            date=date,
            index=activity.day,
        )
        activity.day_fk = day
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0040_auto_ticket_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='ratio.Training', verbose_name='Тренинг')),
            ],
            options={
                'verbose_name': 'День тренинга',
                'verbose_name_plural': 'Дни тренинга',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='day_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='ratio.TrainingDay'),
        ),
        migrations.RunPython(
            fill_training_day
        )
    ]
