# Generated by Django 2.2.5 on 2019-11-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0041_training_day_p1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('day_fk__date',), 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='training',
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='ratio.Training', verbose_name='Тренинг'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingday',
            unique_together={('date', 'training')},
        ),
        migrations.RemoveField(
            model_name='trainingday',
            name='index',
        ),
    ]
