# Generated by Django 3.0.3 on 2020-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0043_training_day_p3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='training',
            name='telegram_link',
            field=models.URLField(verbose_name='Телеграм-чат'),
        ),
    ]
