# Generated by Django 3.0.5 on 2020-05-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0044_auto_20200402_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionindexpage',
            options={'verbose_name': 'Список рацио-секций', 'verbose_name_plural': 'Списки рацио-секций'},
        ),
        migrations.AlterModelOptions(
            name='sectionpage',
            options={'verbose_name': 'Рацио-секция', 'verbose_name_plural': 'Рацио-секции'},
        ),
    ]
