# Generated by Django 3.0.5 on 2020-05-22 20:03

from django.db import migrations, models
import django.db.models.deletion
import kocherga.wagtail.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('ratio', '0045_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Список рацио-презентаций',
                'verbose_name_plural': 'Списки рацио-презентаций',
            },
            bases=(kocherga.wagtail.mixins.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PresentationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('source', models.TextField()),
            ],
            options={
                'verbose_name': 'Рацио-презентация',
                'verbose_name_plural': 'Рацио-презентации',
            },
            bases=(kocherga.wagtail.mixins.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
