# Generated by Django 3.0.5 on 2020-07-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0046_presentations_for_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Размер оплаты')),
                ('payment_type', models.CharField(choices=[('kassa', 'Яндекс.Касса'), ('kassa_invoice', 'Счёт Яндекс.Кассы'), ('transfer', 'Перевод'), ('cash', 'Наличные'), ('paypal', 'PayPal'), ('timepad', 'Timepad'), ('other', 'Другое')], default='website', max_length=40, verbose_name='Вид оплаты')),
                ('status', models.CharField(choices=[('todo', 'Не оплачен'), ('paid', 'Оплачен'), ('canceled', 'Отменён')], default='normal', max_length=40, verbose_name='Статус')),
                ('fiscalization_status', models.CharField(choices=[('todo', 'todo'), ('not_needed', 'not_needed'), ('in_progress', 'in_progress'), ('fiscalized', 'fiscalized')], max_length=40, verbose_name='Статус фискального чека')),
                ('comment', models.TextField(blank=True)),
                ('custom_kkm_title', models.CharField(blank=True, max_length=255, verbose_name='Кастомный заголовок для чека')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ratio.Ticket')),
            ],
        ),
    ]
