# Generated by Django 3.0.5 on 2020-08-02 14:36

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0047_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='slides',
            field=wagtail.core.fields.StreamField([('slides_title', wagtail.core.blocks.CharBlock(label='Заголовок'))], blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('kassa', 'Яндекс.Касса'), ('kassa_invoice', 'Счёт Яндекс.Кассы'), ('transfer', 'Перевод'), ('cash', 'Наличные'), ('paypal', 'PayPal'), ('timepad', 'Timepad'), ('other', 'Другое')], max_length=40, verbose_name='Вид оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('todo', 'Не оплачен'), ('paid', 'Оплачен'), ('canceled', 'Отменён')], default='todo', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fiscalization_status',
            field=models.CharField(blank=True, choices=[('todo', 'todo'), ('not_needed', 'not_needed'), ('in_progress', 'in_progress'), ('fiscalized', 'fiscalized')], max_length=40, verbose_name='Статус фискального чека'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('none', '-'), ('timepad', 'Timepad'), ('website', 'Сайт'), ('crowdfunding', 'Краудфандинг'), ('cash', 'Нал'), ('invoice', 'Счёт'), ('transfer', 'Перевод')], default='website', max_length=40, verbose_name='Вид оплаты'),
        ),
    ]
