# Generated by Django 3.0.5 on 2020-08-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('ratio', '0048_stream_slides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['registration_date'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.DeleteModel(
            name='PresentationPage',
        ),
    ]
