# Generated by Django 3.0.10 on 2020-10-20 19:30

from django.db import migrations, models
import django.db.models.deletion
import kocherga.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_kassa', '0001_initial'),
        ('ratio', '0050_ticket_cleanups'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kassa_payment',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ratio_payment',
                to='yandex_kassa.Payment',
            ),
        ),
        migrations.CreateModel(
            name='TicketArticle',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    kocherga.django.fields.ShortUUIDField(
                        default=kocherga.django.fields.generate_uuid, unique=True
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_articles',
                        to='ratio.Training',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    kocherga.django.fields.ShortUUIDField(
                        default=kocherga.django.fields.generate_uuid, unique=True
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_first_name', models.EmailField(blank=True, max_length=254)),
                ('payer_last_name', models.EmailField(blank=True, max_length=254)),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to='ratio.TicketArticle',
                    ),
                ),
                (
                    'payment',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ratio_order',
                        to='yandex_kassa.Payment',
                        verbose_name='Платёж',
                    ),
                ),
            ],
        ),
    ]
