# Generated by Django 3.0.10 on 2020-10-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0051_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketArticle',
            new_name='TicketType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='article',
            new_name='ticket_type',
        ),
    ]
