# Generated by Django 3.0.10 on 2020-10-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0053_tickettype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
