# Generated by Django 3.0.10 on 2020-10-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0055_optional_telegram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, verbose_name='Промокод')),
                ('discount', models.IntegerField(verbose_name='Сумма скидки')),
                ('single_use', models.BooleanField(default=True, verbose_name='Одноразовый')),
                ('last_used', models.DateTimeField(editable=False, null=True, verbose_name='Последнее использование')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratio.TicketType')),
            ],
            options={
                'unique_together': {('code', 'ticket_type')},
            },
        ),
    ]
