# Generated by Django 3.0.10 on 2020-11-01 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0056_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ratio.Promocode'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Promocode must include only a-z or 0-9 characters', regex='^[a-zA-Z0-9]+$')], verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='ratio.TicketType'),
        ),
    ]
