# Generated by Django 3.0.10 on 2020-11-01 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0057_order_promocode_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='single_use',
        ),
        migrations.AddField(
            model_name='promocode',
            name='uses_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество использований'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='uses_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество использований'),
        ),
    ]
