# Generated by Django 3.0.10 on 2020-11-01 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0058_promocode_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='discount_by_email',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Размер одноразового  промокода по E-mail'у"),
        ),
    ]
