# Generated by Django 3.0.10 on 2020-11-01 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0059_discount_by_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='discount_percent_by_email',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Процент скдики одноразового промокода по E-mail'у"),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='promocodes',
            field=models.ManyToManyField(related_name='ticket_type_promocodes', to='ratio.Promocode'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Promocode must include only a-z or 0-9 characters', regex='^[a-zA-Z0-9]+$')], verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='discount_by_email',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Сумма скидки одноразового промокода по E-mail'у"),
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='ticket_type',
        ),
    ]
