# Generated by Django 3.0.10 on 2020-11-01 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0060_m2m_promocodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='discount_by_email',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Сумма скидки одноразового промокода по E-mail'у"),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='discount_percent_by_email',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Процент скдики одноразового промокода по E-mail'у"),
        ),
    ]
