# Generated by Django 3.0.10 on 2020-11-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0062_training_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='for_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Создан для E-mail'а"),
        ),
    ]
