# Generated by Django 3.0.10 on 2020-11-01 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0063_promocode_for_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notion_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Promocode must include only A-Z or 0-9 characters',
                        regex='^[A-Z0-9]+$',
                    )
                ],
                verbose_name='Промокод',
            ),
        ),
    ]
