# Generated by Django 3.0.10 on 2020-11-06 18:40

import datetime

from django.db import migrations, models
import django.utils.timezone

from kocherga.dateutils import TZ


def registration_date_to_created(apps, schema_editor):
    Ticket = apps.get_model('ratio', 'Ticket')
    for ticket in Ticket.objects.all():
        created = datetime.datetime.combine(
            ticket.registration_date, datetime.time.min, tzinfo=TZ
        )
        ticket.created = created
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0065_ratio_email_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Дата создания',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(registration_date_to_created),
    ]
