# Generated by Django 3.0.10 on 2020-11-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0066_ticket_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type',
            new_name='ticket_class',
        ),
    ]
