# Generated by Django 3.1.3 on 2021-03-08 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0072_testimonial_description_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-f]{6}$')])),
                ('link', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Продукт для отзыва',
                'verbose_name_plural': 'Продукты для отзывов',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='ratio.testimonialproduct'),
        ),
    ]
