# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('slack_id', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=1024)),
                ('real_name', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
