# Generated by Django 2.2 on 2019-05-03 15:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'body',
                    wagtail.core.fields.StreamField(
                        [
                            ('header', wagtail.core.blocks.CharBlock()),
                            ('paragraph', wagtail.core.blocks.RichTextBlock()),
                            ('image', wagtail.images.blocks.ImageChooserBlock()),
                        ]
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
    ]
