# Generated by Django 2.2 on 2019-05-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('wagtailcore.page',),
        ),
    ]
