# Generated by Django 2.2 on 2019-05-04 14:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_folderpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField(
                [
                    ('basic_header', wagtail.core.blocks.CharBlock(group='basic')),
                    (
                        'basic_paragraph',
                        wagtail.core.blocks.RichTextBlock(group='basic'),
                    ),
                    (
                        'grey',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('header', wagtail.core.blocks.CharBlock()),
                                (
                                    'text',
                                    wagtail.core.blocks.RichTextBlock(required=False),
                                ),
                            ],
                            group='style',
                        ),
                    ),
                    (
                        'columns_basic',
                        wagtail.core.blocks.ListBlock(
                            wagtail.core.blocks.StructBlock(
                                [
                                    ('header', wagtail.core.blocks.CharBlock()),
                                    (
                                        'text',
                                        wagtail.core.blocks.RichTextBlock(
                                            required=False
                                        ),
                                    ),
                                ]
                            ),
                            group='columns',
                        ),
                    ),
                ]
            ),
        ),
    ]
