# Generated by Django 3.0.5 on 2020-09-16 17:32

import datetime
from django.db import migrations, models
import kocherga.wagtail.blocks
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.images.blocks
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_social_links_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=40)),
                ('until', models.DateTimeField()),
                ('hide_duration', models.DurationField(default=datetime.timedelta(days=7))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='freeformpage',
            name='body',
            field=wagtail.core.fields.StreamField([('grey', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))], group='basic', icon='title', label='Заголовок секции')), ('basic_lead', kocherga.wagtail.blocks.SafeRichTextBlock(group='basic', icon='bold', label='Крупный текст')), ('basic_text', wagtail.core.blocks.StructBlock([('text', kocherga.wagtail.blocks.SafeRichTextBlock()), ('centered', wagtail.core.blocks.BooleanBlock(required=False))], group='basic', icon='doc-full', label='Обычный текст')), ('basic_card', kocherga.wagtail.blocks.SafeRichTextBlock(group='basic', label='Карточка с информацией')), ('section_header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))], group='basic', icon='title', label='Заголовок секции')), ('hr', wagtail.core.blocks.static_block.StaticBlock(group='basic', icon='horizontalrule', label='Горизонтальная линия')), ('columns_basic', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))]), group='columns', label='Колонки')), ('columns_buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Заголовок')), ('text', wagtail.core.blocks.CharBlock(label='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Текст на кнопке')), ('link', kocherga.wagtail.blocks.URLOrAbsolutePathBlock(label='Ссылка'))]), group='columns', label='Колонки с кнопками')), ('events_list', wagtail.core.blocks.static_block.StaticBlock(group='various', icon='list-ul', label='Список событий')), ('big_contacts', wagtail.core.blocks.StructBlock([('map', wagtailgeowidget.blocks.GeoBlock(label='Координаты')), ('address', wagtail.core.blocks.CharBlock(label='Адрес')), ('phone', wagtail.core.blocks.CharBlock(label='Телефон')), ('email', wagtail.core.blocks.CharBlock(label='Email')), ('text', wagtail.core.blocks.CharBlock(label='Текст'))], group='various', icon='site', label='Карта с адресом')), ('photo_ribbon', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), group='various', label='Лента фоток')), ('mailchimp_subscribe', wagtail.core.blocks.StructBlock([('news', wagtail.core.blocks.BooleanBlock(default=True, label='Материалы и новости', required=False)), ('events', wagtail.core.blocks.BooleanBlock(default=True, label='Расписание мероприятий', required=False)), ('trainings', wagtail.core.blocks.BooleanBlock(default=True, label='Уведомления о новых тренингах', required=False))], group='various', label='Форма подписки'))]),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='body',
            field=wagtail.core.fields.StreamField([('grey', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))], group='basic', icon='title', label='Заголовок секции')), ('basic_lead', kocherga.wagtail.blocks.SafeRichTextBlock(group='basic', icon='bold', label='Крупный текст')), ('basic_text', wagtail.core.blocks.StructBlock([('text', kocherga.wagtail.blocks.SafeRichTextBlock()), ('centered', wagtail.core.blocks.BooleanBlock(required=False))], group='basic', icon='doc-full', label='Обычный текст')), ('basic_card', kocherga.wagtail.blocks.SafeRichTextBlock(group='basic', label='Карточка с информацией')), ('section_header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))], group='basic', icon='title', label='Заголовок секции')), ('hr', wagtail.core.blocks.static_block.StaticBlock(group='basic', icon='horizontalrule', label='Горизонтальная линия')), ('columns_basic', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('text', kocherga.wagtail.blocks.SafeRichTextBlock(required=False))]), group='columns', label='Колонки')), ('columns_buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Заголовок')), ('text', wagtail.core.blocks.CharBlock(label='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Текст на кнопке')), ('link', kocherga.wagtail.blocks.URLOrAbsolutePathBlock(label='Ссылка'))]), group='columns', label='Колонки с кнопками')), ('events_list', wagtail.core.blocks.static_block.StaticBlock(group='various', icon='list-ul', label='Список событий')), ('big_contacts', wagtail.core.blocks.StructBlock([('map', wagtailgeowidget.blocks.GeoBlock(label='Координаты')), ('address', wagtail.core.blocks.CharBlock(label='Адрес')), ('phone', wagtail.core.blocks.CharBlock(label='Телефон')), ('email', wagtail.core.blocks.CharBlock(label='Email')), ('text', wagtail.core.blocks.CharBlock(label='Текст'))], group='various', icon='site', label='Карта с адресом')), ('photo_ribbon', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), group='various', label='Лента фоток')), ('mailchimp_subscribe', wagtail.core.blocks.StructBlock([('news', wagtail.core.blocks.BooleanBlock(default=True, label='Материалы и новости', required=False)), ('events', wagtail.core.blocks.BooleanBlock(default=True, label='Расписание мероприятий', required=False)), ('trainings', wagtail.core.blocks.BooleanBlock(default=True, label='Уведомления о новых тренингах', required=False))], group='various', label='Форма подписки')), ('hero_front', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Заголовок')), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Текст')), ('link', kocherga.wagtail.blocks.URLOrAbsolutePathBlock(label='Ссылка', required=False)), ('highlight', wagtail.core.blocks.BooleanBlock(default=False, label='Важная кнопка', required=False))]), label='Кнопки'))], group='various', icon='home')), ('front_partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('link', kocherga.wagtail.blocks.URLOrAbsolutePathBlock(label='Ссылка', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock())]), group='various', label='Партнёры')), ('front_social_links', wagtail.core.blocks.static_block.StaticBlock(group='various', label='Ссылки на соцсети'))]),
        ),
    ]
