apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: hcloud-csi
        chartPath: ops/charts/hcloud-csi
        valuesFiles:
          - ops/secrets/hcloud-csi.yaml
        wait: true

      - name: cert-manager
        chartPath: ops/charts/cert-manager
        wait: true

      - name: cert-manager-issuers
        chartPath: ops/charts/cert-manager-issuers
        wait: true

      - name: traefik
        namespace: tt
        chartPath: ops/charts/traefik
        wait: true
