apiVersion: skaffold/v2beta16
kind: Config
deploy:
  helm:
    releases:
    - name: elasticsearch
      remoteChart: elastic/elasticsearch
      valuesFiles:
      - ops/values/elasticsearch.yaml
      wait: true
      upgradeOnChange: true
    - name: kibana
      remoteChart: elastic/kibana
      version: 7.8.0
      wait: true
    flags:
      upgrade:
      - --install
