apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: metabase
        chartPath: ops/charts/metabase
        valuesFiles:
          - ops/secrets/metabase.yaml
