apiVersion: skaffold/v2beta16
kind: Config
deploy:
  helm:
    releases:
    - name: metabase
      chartPath: ops/charts/metabase
      valuesFiles:
      - ops/secrets/metabase.yaml
    flags:
      upgrade:
      - --install
