apiVersion: skaffold/v2beta5
kind: Config
deploy:
  helm:
    releases:
      - name: monitor
        # https://github.com/helm/charts/tree/master/stable/prometheus-operator
        chartPath: stable/prometheus-operator
        valuesFiles:
          - ops/values/prometheus.yaml
          - ops/secrets/prometheus.yaml
        namespace: monitor
        wait: true
        remote: true
        upgradeOnChange: true
      - name: loki
        # https://grafana.github.io/loki/charts/
        chartPath: loki/loki-stack
        namespace: monitor
        wait: true
        remote: true
        upgradeOnChange: true
    flags:
      upgrade:
        - --install
