apiVersion: skaffold/v2beta5
kind: Config
deploy:
  helm:
    releases:
      - name: monitor
        # https://github.com/helm/charts/tree/master/stable/prometheus-operator
        chartPath: prometheus-community/kube-prometheus-stack
        valuesFiles:
          - ops/values/prometheus.yaml
          - ops/secrets/prometheus.yaml
        namespace: monitor
        wait: true
        remote: true
        upgradeOnChange: true
      - name: fluentd
        chartPath: ops/charts/fluentd
        namespace: monitor
        wait: true
    flags:
      upgrade:
        - --install
