apiVersion: skaffold/v2beta5
kind: Config
deploy:
  helm:
    releases:
    - name: monitor
      chartPath: stable/prometheus-operator
      valuesFiles:
      - ops/values/prometheus.yaml
      - ops/secrets/prometheus.yaml
      namespace: monitor
      wait: true
      remote: true
    flags:
      upgrade:
      - --install
