apiVersion: skaffold/v2beta16
kind: Config
deploy:
  helm:
    releases:
    - name: monitor
      # https://github.com/prometheus-community/helm-charts
      remoteChart: prometheus-community/kube-prometheus-stack
      valuesFiles:
      - ops/values/prometheus.yaml
      - ops/secrets/prometheus.yaml
      namespace: monitor
      wait: true
      upgradeOnChange: true
    - name: fluentd
      chartPath: ops/charts/fluentd
      namespace: monitor
      wait: true
    flags:
      upgrade:
      - --install
