apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: vault
        namespace: vault
        chartPath: ops/charts/vault
        valuesFiles:
          - ops/secrets/vault.yaml
