apiVersion: skaffold/v2beta16
kind: Config
deploy:
  helm:
    releases:
    - name: vault
      chartPath: ops/charts/vault
      valuesFiles:
      - ops/secrets/vault.yaml
      namespace: vault
    flags:
      upgrade:
      - --install
