apiVersion: skaffold/v2beta16
kind: Config
deploy:
  helm:
    releases:
    - name: verdaccio
      remoteChart: stable/verdaccio
      valuesFiles:
      - ops/values/verdaccio.yaml
      wait: true
    flags:
      upgrade:
      - --install
