apiVersion: skaffold/v2beta5
kind: Config
deploy:
  helm:
    releases:
    - name: verdaccio
      chartPath: stable/verdaccio
      valuesFiles:
      - ops/values/verdaccio.yaml
      wait: true
      remote: true
    flags:
      upgrade:
      - --install
