apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/mediawiki
    context: ops/images/mediawiki
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: kocherga-wiki
        chartPath: ops/charts/wiki
        values:
          image: registry.gitlab.com/kocherga/core/mediawiki
        valuesFiles:
          - ops/values/kocherga-wiki.yaml
          - ops/secrets/kocherga-wiki.yaml
      - name: berekuk-wiki
        chartPath: ops/charts/wiki
        namespace: berekuk
        values:
          image: registry.gitlab.com/kocherga/core/mediawiki
        valuesFiles:
          - ops/values/berekuk-wiki.yaml
          - ops/secrets/berekuk-wiki.yaml
