apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kocherga/core/mediawiki
    context: ops/images/mediawiki
  - image: registry.gitlab.com/kocherga/core/mysql-backup
    context: ops/images/mysql-backup
deploy:
  helm:
    releases:
    - name: kocherga-wiki
      chartPath: ops/charts/wiki
      valuesFiles:
      - ops/values/kocherga-wiki.yaml
      - ops/secrets/kocherga-wiki.yaml
      artifactOverrides:
        image.mysql_backup: registry.gitlab.com/kocherga/core/mysql-backup
        image.wiki: registry.gitlab.com/kocherga/core/mediawiki
    - name: berekuk-wiki
      chartPath: ops/charts/wiki
      valuesFiles:
      - ops/values/berekuk-wiki.yaml
      - ops/secrets/berekuk-wiki.yaml
      artifactOverrides:
        image.mysql_backup: registry.gitlab.com/kocherga/core/mysql-backup
        image.wiki: registry.gitlab.com/kocherga/core/mediawiki
      namespace: berekuk
    flags:
      upgrade:
      - --install
