"""cm_longer_comment

Revision ID: 37d8ef2f0036
Revises: 3d76edf78ad4
Create Date: 2018-05-20 19:09:34.796254+03:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37d8ef2f0036'
down_revision = '3d76edf78ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cm_orders', 'comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cm_orders', 'comment',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
