"""cm_imported_timestamps

Revision ID: 3d76edf78ad4
Revises: e019272120d9
Create Date: 2018-05-20 19:05:53.530780+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d76edf78ad4'
down_revision = 'e019272120d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cm_orders', sa.Column('imported_ts', sa.Integer(), nullable=True))
    op.add_column('cm_orders', sa.Column('log_imported_ts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cm_orders', 'log_imported_ts')
    op.drop_column('cm_orders', 'imported_ts')
    # ### end Alembic commands ###
