"""intiial

Revision ID: 423ab29086b7
Revises: 
Create Date: 2018-04-07 04:14:35.520603+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423ab29086b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('shift', sa.String(length=40), nullable=True),
    sa.Column('watchman', sa.String(length=100), nullable=True),
    sa.Column('cash_income', sa.Integer(), nullable=True),
    sa.Column('electronic_income', sa.Integer(), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.Column('current_cash', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discrepancy', sa.Integer(), nullable=True),
    sa.Column('spendings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'shift', name='cashier_shift_pair')
    )
    op.create_table('cm_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('visit_length', sa.Integer(), nullable=True),
    sa.Column('full_visit_length', sa.Integer(), nullable=True),
    sa.Column('order_value', sa.Integer(), nullable=True),
    sa.Column('time_value', sa.Integer(), nullable=True),
    sa.Column('stuff_value', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('is_fixed', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('tariff_time', sa.String(length=20), nullable=True),
    sa.Column('tariff_plan', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('events',
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('google_link', sa.String(length=255), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('updated_ts', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('master_id', sa.String(length=100), nullable=True),
    sa.Column('visitors', sa.String(length=100), nullable=True),
    sa.Column('asked_for_visitors_ts', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('vk_group', sa.String(length=40), nullable=True),
    sa.Column('fb_group', sa.String(length=40), nullable=True),
    sa.Column('has_default_image', sa.Boolean(), nullable=True),
    sa.Column('has_vk_image', sa.Boolean(), nullable=True),
    sa.Column('ready_to_post', sa.Boolean(), nullable=True),
    sa.Column('posted_fb', sa.String(length=255), nullable=True),
    sa.Column('posted_timepad', sa.String(length=255), nullable=True),
    sa.Column('posted_vk', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('google_id')
    )
    op.create_table('gitlab_issue_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('updated_ts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gitlab_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('updated_ts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importers_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importers_log_name'), 'importers_log', ['name'], unique=False)
    op.create_table('importers_state',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('until_ts', sa.Integer(), nullable=True),
    sa.Column('last_ts', sa.Integer(), nullable=True),
    sa.Column('last_exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ofd_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electronic', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_type', sa.Enum('income', 'refund_income', 'expense', 'refund_expense', name='checktype'), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('operator_inn', sa.BigInteger(), nullable=True),
    sa.Column('fiscal_sign', sa.BigInteger(), nullable=True),
    sa.Column('midday_ts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tochka_records',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchmen_schedule',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING_V1', 'EVENING_V1', 'MORNING', 'MIDDAY', 'EVENING', 'NIGHT', name='shift'), nullable=False),
    sa.Column('watchman', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('date', 'shift')
    )
    op.create_index(op.f('ix_watchmen_schedule_watchman'), 'watchmen_schedule', ['watchman'], unique=False)
    op.create_table('zadarma_calls',
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('call_type', sa.Enum('incoming', 'outcoming', name='calltype'), nullable=True),
    sa.Column('internal_number', sa.String(length=100), nullable=True),
    sa.Column('caller_number', sa.String(length=100), nullable=True),
    sa.Column('destination_number', sa.String(length=100), nullable=True),
    sa.Column('disposition', sa.Enum('answered', 'no_answer', 'busy', 'call_failed', 'parse_failed', name='disposition'), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('wait_seconds', sa.Integer(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('watchman', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('call_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadarma_calls')
    op.drop_index(op.f('ix_watchmen_schedule_watchman'), table_name='watchmen_schedule')
    op.drop_table('watchmen_schedule')
    op.drop_table('tochka_records')
    op.drop_table('ofd_documents')
    op.drop_table('importers_state')
    op.drop_index(op.f('ix_importers_log_name'), table_name='importers_log')
    op.drop_table('importers_log')
    op.drop_table('gitlab_issues')
    op.drop_table('gitlab_issue_notes')
    op.drop_table('events')
    op.drop_table('cm_orders')
    op.drop_table('cashier')
    # ### end Alembic commands ###
