"""cm_subscription_orders

Revision ID: 55577efe0b5b
Revises: 0d05608546ab
Create Date: 2018-04-30 23:47:06.379986+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55577efe0b5b'
down_revision = '0d05608546ab'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('cm_subscription_orders',
        sa.Column('card_id', sa.Integer(), nullable=False),
        sa.Column('ts', sa.Integer(), nullable=False),
        sa.Column('order_value', sa.Integer(), nullable=True),
        sa.Column('payment_type', sa.String(length=20), nullable=True),
        sa.Column('client_name', sa.String(length=255), nullable=True),
        sa.Column('manager', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('card_id', 'ts')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cm_subscription_orders')
    # ### end Alembic commands ###
