# Generated by Django 2.1.7 on 2019-02-19 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kocherga_auth', '0002_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('photo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.IntegerField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='mastermind_bot.User')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to='mastermind_bot.User')),
            ],
        ),
    ]
