# Generated by Django 2.1.7 on 2019-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BinaryField(null=True),
        ),
    ]
