# Generated by Django 2.1.7 on 2019-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_bot', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
