# Generated by Django 2.1.7 on 2019-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_bot', '0003_auto_20190220_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
