# Generated by Django 2.1.7 on 2019-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_bot', '0004_auto_20190220_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
