version: '3.4'

x-backend-environment: &backend-environment
  DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'
  DB_NAME: 'kocherga'
  DB_USER: 'root'
  DB_PASSWORD: ''
  prometheus_multiproc_dir: /tmp # TODO - create empty tmpfs dir to avoid file name collisions etc.
  DJANGO_WATCHMAN_TIMEOUT: 60

x-frontend-environment: &frontend-environment
  NODE_ENV: 'development'

x-backend:
  &backend
  image: registry.gitlab.com/kocherga/core/backend:dev
  volumes:
    - ../backend/kocherga:/code/kocherga
    - ../backend/tests:/code/tests
    - ../backend/data/volume:/data
  environment:
    <<: *backend-environment
  cap_add:
    - SYS_PTRACE

x-frontend:
  &frontend
  image: registry.gitlab.com/kocherga/core/frontend:dev
  volumes:
    - ../frontend/jsx:/code/jsx
    - ../backend/data/volume:/data
  environment:
    <<: *frontend-environment
  cap_add:
    - SYS_PTRACE

services:
  worker:
    <<: *backend
    command: ./scripts/worker.py
    depends_on:
      - db

  importer:
    <<: *backend
    command: ./scripts/importer.py
    ports:
      - "127.0.0.1:${IMPORTER_PORT}:8000" # for prometheus metrics
    environment:
      <<: *backend-environment
      NO_DJANGO_PROMETHEUS: 1
    depends_on:
      - db
    restart: always

  tgbot:
    <<: *backend
    command: ./scripts/tgbot.py
    depends_on:
      - db
      - tor

  tor:
    image: dperson/torproxy

  ludwig:
    <<: *backend
    command: ./scripts/ludwig.py
    ports:
      - "${LUDWIG_PORT}:80"
    depends_on:
      - db

  ludwig_lt:
    <<: *frontend
    command: npx lt --port 80 --subdomain kocherga-dev --local-host ludwig --host https://lt.berekuk.ru
    depends_on:
      - ludwig
