version: '3.4'

x-environment: &environment
  DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'
  DB_NAME: 'kocherga'
  DB_USER: 'root'
  DB_PASSWORD: ''
  NODE_ENV: 'development'
  prometheus_multiproc_dir: /tmp # TODO - create empty tmpfs dir to avoid file name collisions etc.
  DJANGO_WATCHMAN_TIMEOUT: 60

x-common: &common
  image: registry.gitlab.com/kocherga/core:dev
  volumes:
    # mac volumes are managed with docker-sync for better performance and inotify fixes
    - code-jsx:/code/jsx:nocopy
    - code-py:/code/kocherga:nocopy
    - code-pytest:/code/tests:nocopy
    - data:/data:nocopy
  environment:
    <<: *environment
  cap_add:
    - SYS_PTRACE

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: kocherga
    volumes:
      - ../data/db-volume:/var/lib/mysql
      - ../mysql.conf.d:/etc/mysql/conf.d

  chrome:
    image: registry.gitlab.com/kocherga/core/chrome:dev
    build:
      context: .
      dockerfile: ./Dockerfile.chrome
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:9222:9222"
    privileged: true

  redis:
    image: redis:5.0
    ports:
      - "127.0.0.1:6379:6379"

  api:
    << : *common
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        NPM_TOKEN: ${TOKEN}
    command: ./manage.py runserver 0.0.0.0:80
    ports:
      - "127.0.0.1:8001:80"
    depends_on:
      - db
      - chrome
      - redis
      - tor
    restart: always

  channels-worker:
    << : *common
    command: ./scripts/channels-worker.sh
    depends_on:
      - db
      - redis
    restart: always

  tor:
    image: dperson/torproxy

volumes:
  code-jsx:
    external: true
  code-py:
    external: true
  code-pytest:
    external: true
  data:
    external: true
