version: '3.4'

x-common:
  &common
  image: registry.gitlab.com/kocherga/code/core:${TAG}
  extra_hosts:
    - "db:${HOST_IP}"
  environment:
    DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.prod'
  volumes:
    - /data/kocherga:/data
    - /config/dev_secrets.py:/code/kocherga/django/settings/dev_secrets.py


services:
  api:
    << : *common
    command: poetry run gunicorn -w 4 -t 180 -b 0.0.0.0:80 kocherga.django.wsgi
    ports:
      - "5300:80"
    depends_on:
      - render-server

  render-server:
    << : *common
    command: /usr/bin/node ./static/dist/render-server.js

  tgbot:
    << : *common
    command: poetry run ./scripts/tgbot.py

  ludwig:
    << : *common
    command: poetry run ./scripts/ludwig.py
    ports:
      - "5200:80"

  importer:
    << : *common
    command: poetry run ./scripts/importer.py

  worker:
    << : *common
    command: poetry run ./scripts/worker.py
