version: '3.4'

x-environment: &environment
  DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'

x-common: &common
  image: registry.gitlab.com/kocherga/core:dev
  volumes:
    - ..:/code
    - ../data/volume:/data
  environment:
    <<: *environment

services:
  worker:
    << : *common
    command: ./scripts/worker.py
    depends_on:
      - db

  importer:
    << : *common
    command: ./scripts/importer.py
    ports:
      - "127.0.0.1:5303:8000" # for prometheus metrics
    environment:
      << : *environment
      NO_DJANGO_PROMETHEUS: 1
    depends_on:
      - db
    restart: always

  tgbot:
    << : *common
    command: ./scripts/tgbot.py
    depends_on:
      - db
      - tor

  tor:
    image: dperson/torproxy

  ludwig:
    << : *common
    command: ./scripts/ludwig.py
    ports:
      - "5200:80"
    depends_on:
      - db

  ludwig_lt:
    << : *common
    command: npx lt --port 80 --subdomain kocherga-dev --local-host ludwig
    depends_on:
      - ludwig
