version: '3.4'

x-common:
  &common
  image: registry.gitlab.com/kocherga/core:dev
  volumes:
    - ..:/code
    - /data/kocherga:/data
  environment:
    DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'

services:
  worker:
    << : *common
    command: ./scripts/worker.py
    depends_on:
      - db

  importer:
    << : *common
    command: ./scripts/importer.py
    depends_on:
      - db

  tgbot:
    << : *common
    command: ./scripts/tgbot.py
    # TODO - expose RPC port
    depends_on:
      - db

  ludwig:
    << : *common
    command: ./scripts/ludwig.py
    ports:
      - "5200:80"
    depends_on:
      - db

  ludwig_lt:
    << : *common
    command: npx lt --port 80 --subdomain kocherga-dev --local-host ludwig
    depends_on:
      - ludwig
