version: '3.4'

x-backend:
  &backend
  environment:
    DJANGO_WATCHMAN_TIMEOUT: 60
  cap_add:
    - SYS_PTRACE

x-frontend:
  &frontend
  cap_add:
    - SYS_PTRACE

services:
  chrome:
    image: registry.gitlab.com/kocherga/core/chrome:dev
    build:
      context: .
      dockerfile: ./Dockerfile.chrome
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:9222:9222"
    privileged: true

  api:
    << : *backend
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    command: ./manage.py runserver 0.0.0.0:80
    ports:
      - "127.0.0.1:${API_PORT}:80"
    depends_on:
      - db
      - chrome
      - redis
    restart: always

  channels-worker:
    << : *backend
    command: ./scripts/channels-worker.sh
    depends_on:
      - db
      - redis
    restart: always
