version: '3.4'

x-common:
  &common
  image: registry.gitlab.com/kocherga/core:dev
  volumes:
    - ..:/code
    - /data/kocherga:/data
  environment:
    DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'
    DB_NAME: 'kocherga'
    DB_USER: 'root'
    DB_PASSWORD: ''
    NODE_ENV: 'development'
  cap_add:
    - SYS_PTRACE

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - /data/kocherga-db:/var/lib/mysql
      - ../mysql.conf.d:/etc/mysql/conf.d

  chrome:
    image: registry.gitlab.com/kocherga/core/chrome:dev
    build:
      context: .
      dockerfile: ./Dockerfile.chrome
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:9222:9222"
    privileged: true

  redis:
    image: redis:5.0
    ports:
      - "127.0.0.1:6379:6379"

  api:
    << : *common
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        NPM_TOKEN: ${TOKEN}
    command: npx nodemon -w ./kocherga --exec ./manage.py runserver --noreload 0.0.0.0:80
    ports:
      - "127.0.0.1:8001:80"
    depends_on:
      - db
      - chrome
      - redis
    restart: always

  channels-worker:
    << : *common
    command: npx nodemon -w ./kocherga --exec ./scripts/channels-worker.sh
    depends_on:
      - db
      - redis
    restart: always

  render-server:
    << : *common
    command: bash -c 'cd jsx && node ./render/server/index.js'
    depends_on:
      - api
    ports:
      - "127.0.0.1:8000:80"
