# Generated by Django 2.1.7 on 2019-03-28 22:28

from django.db import migrations, models
import kocherga.zadarma.models
import kocherga.zadarma.models.call


class Migration(migrations.Migration):

    dependencies = [
        ('zadarma', '0003_call_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={
                'ordering': ['-ts'],
                'permissions': (('listen', 'Может слушать  звонки'),),
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(
                blank=True, upload_to=kocherga.zadarma.models.call.call_path
            ),
        ),
    ]
