# Generated by Django 2.2 on 2019-05-25 22:00

from django.db import migrations, models
import django.db.models.deletion


def fill_pbx_fk(apps, schema_editor):
    Call = apps.get_model('zadarma', 'Call')
    PbxCall = apps.get_model('zadarma', 'PbxCall')
    for call in Call.objects.all():
        (pbx_call, _) = PbxCall.objects.get_or_create(pk=call.pbx_call_id)
        call.pbx_call_fk = pbx_call
        call.save()


class Migration(migrations.Migration):

    dependencies = [
        ('zadarma', '0004_auto_20190329_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbxCall',
            fields=[
                (
                    'pbx_call_id',
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='pbx_call_fk',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='zadarma.PbxCall',
            ),
        ),
        migrations.RunPython(fill_pbx_fk, lambda x, y: None),
    ]
