# Generated by Django 2.2 on 2019-05-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadarma', '0006_pbx_fk2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='pbx_call_fk',
            new_name='pbx_call',
        ),
    ]
