# Generated by Django 2.2 on 2019-05-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadarma', '0009_pbx_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-ts'], 'permissions': (('listen', 'Может слушать звонки'), ('admin', 'Может администрировать звонки')), 'verbose_name': 'Звонок', 'verbose_name_plural': 'Звонки'},
        ),
        migrations.AlterModelOptions(
            name='pbxcall',
            options={'ordering': ['-ts'], 'verbose_name': 'АТС-звонок', 'verbose_name_plural': 'АТС-звонки'},
        ),
    ]
