# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('checkboxes', 'checkboxes'), ('dropdown', 'dropdown'), ('radio', 'radio'), ('hidden', 'hidden')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MailchimpInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('subscriber_count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='email.mailchimpcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('interests', models.ManyToManyField(to='email.MailchimpInterest')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeChannelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='email.subscribechannel')),
            ],
        ),
    ]
