# Generated by Django 2.2.5 on 2019-10-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_subscribechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimpinterest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='email.MailchimpCategory'),
            preserve_default=False,
        ),
    ]
