# Generated by Django 3.2.4 on 2021-06-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0004_subscribe_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribechannellog',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='email.subscribechannel'),
        ),
    ]
