# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import kocherga.analytics.timeclub24.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeclub24Visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default=kocherga.analytics.timeclub24.models.dt_now)),
                ('venue', models.CharField(max_length=100)),
                ('visitors', models.IntegerField()),
            ],
            options={
                'db_table': 'timeclub24_visitors',
                'unique_together': {('ts', 'venue')},
            },
        ),
    ]
