# Generated by Django 2.2 on 2019-08-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_auth', '0002_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('audit', 'Может проверять права доступа'),), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
