# Generated by Django 3.0.5 on 2020-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_auth', '0003_audit_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
