# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_squash_2021'),
        ('comments', '0001_squash_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_squash_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='events',
            field=models.ManyToManyField(related_name='community_leads', to='events.Event'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='comments',
            field=models.ManyToManyField(related_name='community_initiative', related_query_name='community_initiative', to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='curated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_initiatives', to='events.event'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='leads',
            field=models.ManyToManyField(related_name='initiatives', to='community.Lead'),
        ),
    ]
