# Generated by Django 3.1.3 on 2020-12-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_lead_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'default_permissions': (), 'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
