# Generated by Django 3.1.3 on 2020-12-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('community', '0005_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(related_name='community_lead', related_query_name='community_lead', to='comments.Comment'),
        ),
    ]
