# Generated by Django 3.1.3 on 2020-12-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_lead_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
