# Generated by Django 3.1.3 on 2020-12-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20201208_0459'),
        ('community', '0007_markdown_lead_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='events',
            field=models.ManyToManyField(related_name='community_leads', to='events.Event'),
        ),
    ]
