# Generated by Django 3.1.3 on 2021-06-04 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_markdown_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0060_initiative'),
        ('community', '0008_lead_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный')], db_index=True, default='ACTIVE', max_length=20)),
                ('comments', models.ManyToManyField(related_name='community_initiative', related_query_name='community_initiative', to='comments.Comment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_initiatives', to='events.event')),
                ('leads', models.ManyToManyField(related_name='initiatives', to='community.Lead')),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': (),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
