# Generated by Django 2.1.5 on 2019-01-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Звонок', 'verbose_name_plural': 'Звонки'},
        ),
    ]
