# Generated by Django 2.2 on 2019-05-25 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_pbx_staff_member'),
        ('zadarma', '0008_pbx_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbxCallData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbx_call', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='zadarma.PbxCall')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.Member')),
            ],
        ),
    ]
