apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: metabase
  labels:
    app: metabase
data:
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
  labels:
    app: metabase
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: metabase
  selector:
    app: metabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase
  labels:
    app: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.34.0"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_DB_TYPE
            value: mysql
          - name: MB_DB_HOST
            value: metabase-mysql
          - name: MB_DB_DBNAME
            value: metabase
          - name: MB_DB_USER
            value: metabase
          - name: MB_DB_PASS
            valueFrom:
              secretKeyRef:
                name: metabase-secret
                key: db_password
          - name: MB_PASSWORD_COMPLEXITY
            value: normal
          - name: MB_PASSWORD_LENGTH
            value: "6"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
      volumes:
