# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.CharField(max_length=20, unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(null=True)),
                ('join_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'permissions': (('view_participants', 'Может просматривать участников созвонов'),),
            },
        ),
        migrations.CreateModel(
            name='MeetingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_uuid', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='zoom.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.CharField(max_length=40)),
                ('zoom_user_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=256)),
                ('user_email', models.CharField(max_length=256)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('meeting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zoom.meetinginstance')),
            ],
        ),
    ]
