# Generated by Django 3.0.5 on 2020-05-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_join_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='zoom_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
