# Generated by Django 3.0.5 on 2020-05-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_optional_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
