# Generated by Django 3.0.5 on 2020-05-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0006_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='zoom_user_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
