# Generated by Django 3.0.5 on 2020-05-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0007_participant_zoom_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={
                'permissions': (
                    ('view_participants', 'Может просматривать участников созвонов'),
                )
            },
        ),
    ]
