# Generated by Django 3.0.5 on 2020-05-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0008_details_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='zoom_uuid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='meeting',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='MeetingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_uuid', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='zoom.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='meeting_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zoom.MeetingInstance', null=True),
            preserve_default=False,
        ),
    ]
