# Generated by Django 2.1.7 on 2019-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepad', '0002_auto_20190222_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
