# Generated by Django 2.1.7 on 2019-02-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepad', '0004_auto_20190222_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='timepad.Event'),
        ),
    ]
