# Generated by Django 2.2.5 on 2019-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepad', '0006_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subscribed_to_newsletter',
            field=models.BooleanField(),
        ),
    ]
