kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs.yaml") . | sha256sum }}
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: traefik-ingress-lb
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/traefik/traefik.yaml
              subPath: traefik.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefik
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 8080
      name: admin

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: monitor
spec:
  jobLabel: traefik
  selector:
    matchLabels:
      app: traefik
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: admin
    path: /metrics
    interval: 30s
