# Generated by Django 2.2.5 on 2019-12-04 11:38

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='page',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entries',
                to='faq.FAQPage',
            ),
        ),
    ]
