# Generated by Django 3.0.3 on 2020-04-01 23:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_page_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='answer',
            field=wagtail.core.fields.RichTextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='question',
            field=models.CharField(max_length=4096, verbose_name='Вопрос'),
        ),
    ]
