# Generated by Django 2.1.5 on 2019-01-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0003_auto_20190115_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardimage',
            old_name='image',
            new_name='image_link',
        ),
    ]
