# Generated by Django 2.1.5 on 2019-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0002_auto_20190207_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='Дата регистрации'),
        ),
    ]
