# Generated by Django 2.1.5 on 2019-02-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0009_training_mailchimp_interest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(verbose_name='День')),
                ('time', models.TimeField(verbose_name='Время')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('trainer', models.CharField(blank=True, max_length=255, verbose_name='Ведущий')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='ratio.Training', verbose_name='Тренинг')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('normal', 'Участник'), ('canceled', 'Отказ')], default='normal', max_length=40, verbose_name='Статус'),
        ),
    ]
