# Generated by Django 2.2 on 2019-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0020_auto_20190502_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
