# Generated by Django 2.2 on 2019-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0027_auto_20190506_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='status',
            field=models.CharField(choices=[('test', 'Тест'), ('placeholder', 'Заглушка'), ('in_progress', 'В разработке'), ('editing', 'Редактура'), ('ready', 'Готово')], default='placeholder', max_length=40, verbose_name='Статус'),
        ),
    ]
