# Generated by Django 2.2 on 2019-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratio', '0028_sectionpage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebookpage',
            options={'verbose_name': 'Рабочая тетрадь', 'verbose_name_plural': 'Рабочие тетради'},
        ),
        migrations.AlterModelOptions(
            name='sectionpage',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
