apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redirector
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-redirector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redirector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-redirector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redirector
    spec:
      containers:
        - name: default
          image: nginx:1.17.8
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-redirector-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redirector-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: {{ .Values.redirector.nginx_conf | quote }}
