{{ if .Values.domain -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
  - hosts:
    - {{ .Values.domain | quote }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-metabase
          servicePort: 80
{{- end }}
