apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metabase
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-metabase
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: metabase
  selector:
    app: {{ .Release.Name }}-metabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metabase
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-metabase
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metabase
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-metabase
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_DB_TYPE
            value: mysql
          - name: MB_DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: MB_DB_DBNAME
            value: metabase
          - name: MB_DB_USER
            value: metabase
          - name: MB_DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: password
          - name: MB_PASSWORD_COMPLEXITY
            value: normal
          - name: MB_PASSWORD_LENGTH
            value: "6"
          - name: MAX_SESSION_AGE
            value: "129600" # 3 months; https://www.metabase.com/docs/latest/operations-guide/changing-session-expiration.html
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "2048Mi"
