apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root_password: {{ required "root_password must be set" .Values.database.root_password | b64enc | quote }}
  password: {{ required "password must be set" .Values.database.password | b64enc | quote }}
