apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-vault
spec:
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
  selector:
    app: {{ .Release.Name }}-vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-vault
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}-vault
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-vault
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: default
          image: vault:1.3.2
          command:
            - "/usr/local/bin/docker-entrypoint.sh"
            - "server"
            - "-config"
            - "/config.hcl"
          ports:
            - containerPort: 8200
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-s3-credentials
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "1024Mi"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          volumeMounts:
            - name: config
              mountPath: /config.hcl
              subPath: config.hcl
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
