apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  AWS_S3_BUCKET: {{ .Values.s3.bucket | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.access_key | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secret_key | quote }}
  AWS_REGION: eu-central-1
