# Generated by Django 2.1.5 on 2019-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion
import kocherga.supplies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                (
                    'id',
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('prodway_page', models.CharField(max_length=255)),
                ('prodway_image', models.CharField(max_length=255)),
            ],
            options={'db_table': 'cookies',},
        ),
        migrations.CreateModel(
            name='CookieCombination',
            fields=[
                ('combination_id', models.AutoField(primary_key=True, serialize=False)),
                ('happy_users', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
            options={'db_table': 'cookie_combinations',},
        ),
        migrations.CreateModel(
            name='CookieCombinationItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_id', models.IntegerField()),
                ('cookie_id', models.CharField(max_length=32)),
                (
                    'combination',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='supplies.CookieCombination',
                    ),
                ),
            ],
            options={'db_table': 'cookie_combination_items',},
        ),
        migrations.CreateModel(
            name='CookiePick',
            fields=[
                ('pick_id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default=kocherga.supplies.models.dt_now)),
                ('cookie_id', models.CharField(max_length=32)),
                ('against_id', models.CharField(max_length=32)),
                ('position', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
            options={'db_table': 'cookie_picks',},
        ),
        migrations.AlterUniqueTogether(
            name='cookiecombinationitem',
            unique_together={('combination', 'position_id')},
        ),
    ]
