prometheus:
  prometheusSpec:      
    retentionSize: "8GB"
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
grafana:
  persistence:
    enabled: true
    size: 10Gi
