# Generated by Django 3.2.4 on 2021-06-06 18:17

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_squash_2021'),
        ('kocherga_wagtail', '0001_squash_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydigest',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.customimage'),
        ),
        migrations.AddField(
            model_name='vkannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vk_announcement', to='events.event'),
        ),
        migrations.AddField(
            model_name='vkannouncement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.customimage'),
        ),
        migrations.AddField(
            model_name='timepadannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timepad_announcement', to='events.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.event'),
        ),
        migrations.AddField(
            model_name='googleevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='google_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='googleevent',
            name='google_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_events', to='events.googlecalendar'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event'),
        ),
        migrations.AddField(
            model_name='fbannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fb_announcement', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventprototypetag',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.eventprototype'),
        ),
        migrations.AddField(
            model_name='eventprototype',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.customimage'),
        ),
    ]
