# Generated by Django 2.1.5 on 2019-01-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventprototypetag',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.EventPrototype'),
        ),
    ]
