# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoom', '0001_squash_2021'),
        ('kocherga_wagtail', '0001_squash_2021'),
        ('events', '0002_squash_2021'),
        ('projects', '0001_squash_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprototype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectpage'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.customimage'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.projectpage'),
        ),
        migrations.AddField(
            model_name='event',
            name='prototype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_events', to='events.eventprototype'),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='zoom.meeting'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='eventprototypetag',
            unique_together={('prototype', 'name')},
        ),
    ]
