# Generated by Django 2.1.5 on 2019-01-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190113_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventprototype',
            options={
                'verbose_name': 'Прототип события',
                'verbose_name_plural': 'Прототипы событий',
            },
        ),
        migrations.AlterModelOptions(
            name='tag', options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
