# Generated by Django 2.2 on 2019-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_ts_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDigest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Дата начала недели')),
                ('mailchimp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID кампании в Mailchimp')),
                ('mailchimp_sent', models.BooleanField(default=False, verbose_name='Mailchimp-кампания отправлена')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сообщения в Telegram')),
                ('vk_id', models.CharField(max_length=100, verbose_name='ID поста в VK')),
            ],
        ),
    ]
