# Generated by Django 2.2 on 2019-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_weeklydigest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydigest',
            name='vk_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID поста в VK'),
        ),
    ]
