# Generated by Django 2.2 on 2019-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_fb_announcement_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydigest',
            name='mailchimp_id',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='ID кампании в Mailchimp',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklydigest',
            name='telegram_id',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='ID сообщения в Telegram',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklydigest',
            name='vk_id',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='ID поста в VK'
            ),
            preserve_default=False,
        ),
    ]
