# Generated by Django 2.2 on 2019-08-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_nonnull_digest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fb_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='posted_fb',
        ),
        migrations.RemoveField(
            model_name='event',
            name='posted_timepad',
        ),
        migrations.RemoveField(
            model_name='event',
            name='posted_vk',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timepad_category_code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timepad_prepaid_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vk_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vk_image',
        ),
    ]
