# Generated by Django 2.2.5 on 2019-10-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectindexpage'),
        ('events', '0021_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprototype',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='projects.ProjectPage',
            ),
        ),
    ]
