# Generated by Django 2.2.5 on 2019-10-19 22:24

from django.db import migrations, models


def fill_google_ids(apps, schema_editor):
    for model_name in (
        'Ticket',
        'Tag',
        'VkAnnouncement',
        'FbAnnouncement',
        'TimepadAnnouncement',
    ):
        model_class = apps.get_model('events', model_name)
        for obj in model_class.objects.all():
            obj.event_google_id = obj.event_id
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_eventprototype_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkannouncement',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fbannouncement',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepadannouncement',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(fill_google_ids),
    ]
