# Generated by Django 2.2.5 on 2019-10-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_pk_p1'),
    ]

    operations = [
        migrations.RemoveField(model_name='fbannouncement', name='event',),
        migrations.RemoveField(model_name='timepadannouncement', name='event',),
        migrations.RemoveField(model_name='vkannouncement', name='event',),
        migrations.AlterUniqueTogether(name='ticket', unique_together=set(),),
        migrations.RemoveField(model_name='ticket', name='event',),
        migrations.AlterUniqueTogether(name='tag', unique_together=set(),),
        migrations.RemoveField(model_name='tag', name='event',),
    ]
