# Generated by Django 2.2.5 on 2019-10-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_pk_p2'),
        ('mastermind_dating', '0023_event_pk_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
            preserve_default=False,
        ),
    ]
