# Generated by Django 2.2.5 on 2019-10-19 22:56

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_event_pk_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fb_announcement',
                to='events.Event',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='event',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='events.Event',
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='events.Event',
            ),
        ),
        migrations.AddField(
            model_name='timepadannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='timepad_announcement',
                to='events.Event',
            ),
        ),
        migrations.AddField(
            model_name='vkannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vk_announcement',
                to='events.Event',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='tag', unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket', unique_together={('event', 'user')},
        ),
    ]
