# Generated by Django 2.2.5 on 2019-10-19 23:08

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_pk_p5'),
    ]

    operations = [
        migrations.RemoveField(model_name='fbannouncement', name='event_google_id',),
        migrations.RemoveField(model_name='tag', name='event_google_id',),
        migrations.RemoveField(model_name='ticket', name='event_google_id',),
        migrations.RemoveField(
            model_name='timepadannouncement', name='event_google_id',
        ),
        migrations.RemoveField(model_name='vkannouncement', name='event_google_id',),
        migrations.AlterField(
            model_name='fbannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fb_announcement',
                to='events.Event',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='events.Event',
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='events.Event',
            ),
        ),
        migrations.AlterField(
            model_name='timepadannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='timepad_announcement',
                to='events.Event',
            ),
        ),
        migrations.AlterField(
            model_name='vkannouncement',
            name='event',
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vk_announcement',
                to='events.Event',
            ),
        ),
    ]
