# Generated by Django 2.2.5 on 2019-10-20 22:24

from django.db import migrations, models
import kocherga.events.models.event

import base64
import uuid


def populate_uuids(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    for obj in Event.objects.all():
        obj.uuid = base64.b32encode(uuid.uuid4().bytes)[:26].lower().decode('ascii')
        obj.save()


def nop(x, y):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_pk_p6'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.SlugField(default=kocherga.events.models.event.generate_uuid),
        ),
        migrations.RunPython(populate_uuids, nop),
    ]
