# Generated by Django 2.2.5 on 2019-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_googlecalendar_googleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='public_only',
            field=models.BooleanField(default=True),
        ),
    ]
