# Generated by Django 2.2.5 on 2019-10-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_invite_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_link',
        ),
    ]
