# Generated by Django 2.2.5 on 2019-10-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback', name='comment', field=models.TextField(blank=True),
        ),
    ]
