# Generated by Django 2.2.5 on 2019-10-24 11:34

import django.core.validators
from django.db import migrations, models
import kocherga.events.models.feedback


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_feedback_comment_optional'),
    ]

    operations = [
        migrations.RemoveField(model_name='feedback', name='source',),
        migrations.AddField(
            model_name='feedback',
            name='source_email',
            field=models.BooleanField(
                default=False, verbose_name='Откуда / Почтовая рассылка'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_fb',
            field=models.BooleanField(default=False, verbose_name='Откуда / Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_friend',
            field=models.BooleanField(default=False, verbose_name='Откуда / Знакомые'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_timepad',
            field=models.BooleanField(default=False, verbose_name='Откуда / Timepad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_vk',
            field=models.BooleanField(default=False, verbose_name='Откуда / ВКонтакте'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_website',
            field=models.BooleanField(
                default=False, verbose_name='Откуда / Сайт Кочерги'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='conductor_score',
            field=kocherga.events.models.feedback.ScoreField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name='Насколько вы довольны работой ведущих?',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_score',
            field=kocherga.events.models.feedback.ScoreField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name='Насколько вам было интересно содержание?',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='custom_source',
            field=models.CharField(
                blank=True,
                max_length=1024,
                verbose_name='Откуда вы узнали про мероприятие? (свой вариант)',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_score',
            field=kocherga.events.models.feedback.ScoreField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name='Насколько вам понравилось мероприятие в целом?',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recommend_score',
            field=kocherga.events.models.feedback.ScoreField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name='Насколько вероятно, что вы порекомендуете такое мероприятие знакомым?',
            ),
        ),
    ]
