# Generated by Django 2.2.5 on 2019-10-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_feedback_boolean_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_tickets', 'Может смотреть все билеты'),)},
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(
                choices=[('ok', 'ОК'), ('inactive', 'Отказ')],
                default='ok',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
