# Generated by Django 2.2.5 on 2019-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_ticket_day_before_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
