# Generated by Django 2.2.5 on 2019-11-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_ticket_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ready_to_post',
            new_name='published',
        ),
    ]
