# Generated by Django 2.2.5 on 2019-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_ticket_from_timepad'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.CharField(
                choices=[('native', 'native'), ('timepad', 'timepad')],
                default='native',
                max_length=20,
            ),
        ),
    ]
