# Generated by Django 2.2.5 on 2020-02-01 22:33
from pathlib import Path

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.core.files.images import ImageFile
from wagtail.images.models import Image


def fill_wagtail_images(apps, schema_editor):
    # Note that we don't use apps.get_model here - it won't work.
    # Hopefully Image class won't change much in the future...
    image_class = Image
    historical_image_class = apps.get_model('wagtailimages', 'Image')

    for model_name in ('Event', 'EventPrototype', 'VkAnnouncement'):
        model_class = apps.get_model('events', model_name)
        for obj in model_class.objects.all():
            if obj.image:
                title = None
                if model_name == 'Event':
                    title = obj.title
                elif model_name == 'EventPrototype':
                    title = obj.title
                elif model_name == 'VkAnnouncement':
                    title = f'{obj.event.title} - VK'

                if model_name == 'Event':
                    filename = f'event-image-{obj.uuid}'
                elif model_name == 'EventPrototype':
                    filename = f'prototype-image-{obj.pk}'
                elif model_name == 'VkAnnouncement':
                    filename = f'vk-announcement-image-{obj.id}'

                fh = open(Path(settings.DATA_DIR) / 'upload' / 'images' / (obj.image + '.jpg'), 'rb')
                image = image_class(title=title)
                image.file.save(filename, ImageFile(fh))
                image.save()

                # Django doesn't accept Image object here because it checks FK type, so we have to reload it with correct class.
                historical_image = historical_image_class.objects.get(pk=image.pk)
                obj.wagtail_image = historical_image

                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('events', '0045_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wagtail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='eventprototype',
            name='wagtail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='vkannouncement',
            name='wagtail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.RunPython(
            fill_wagtail_images,
            lambda *x: None,
        ),
    ]
