# Generated by Django 2.2.5 on 2020-02-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_wagtail_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event', old_name='image', new_name='image_old',
        ),
        migrations.RenameField(
            model_name='eventprototype', old_name='image', new_name='image_old',
        ),
        migrations.RenameField(
            model_name='vkannouncement', old_name='image', new_name='image_old',
        ),
        migrations.RenameField(
            model_name='event', old_name='wagtail_image', new_name='image',
        ),
        migrations.RenameField(
            model_name='eventprototype', old_name='wagtail_image', new_name='image',
        ),
        migrations.RenameField(
            model_name='vkannouncement', old_name='wagtail_image', new_name='image',
        ),
    ]
