# Generated by Django 3.0.3 on 2020-03-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_image_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='realm',
            field=models.CharField(choices=[('offline', 'offline'), ('youtube_broadcast', 'youtube_broadcast')], default='offline', max_length=40),
        ),
    ]
