# Generated by Django 3.0.5 on 2020-06-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kocherga_wagtail', '0003_images_data'),
        ('events', '0055_zoom_meeting_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='kocherga_wagtail.CustomImage',
            ),
        ),
        migrations.AlterField(
            model_name='eventprototype',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='kocherga_wagtail.CustomImage',
            ),
        ),
        migrations.AlterField(
            model_name='vkannouncement',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='kocherga_wagtail.CustomImage',
            ),
        ),
        migrations.AlterField(
            model_name='weeklydigest',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='kocherga_wagtail.CustomImage',
            ),
        ),
    ]
