# Generated by Django 3.0.5 on 2020-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_custom_wagtail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleevent',
            name='html_link',
            field=models.URLField(blank=True),
        ),
    ]
