# Generated by Django 3.1.3 on 2020-11-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0010_cleanups'),
        ('events', '0057_googleevent_html_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage', 'Can manage events and related objects')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='zoom_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='zoom.meeting'),
        ),
    ]
