# Generated by Django 3.1.3 on 2020-12-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_events_manage_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
