# Generated by Django 3.1.3 on 2021-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20201208_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('unknown', 'unknown')], default='public', max_length=40),
        ),
    ]
