apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocherga-frontend
spec:
  template:
    spec:
      containers:
        - name: default
          command: ["./node_modules/.bin/nodemon", "--watch", "dist", "./dist/index.js"]
          env:
            - name: NODE_ENV
              value: development
          volumeMounts:
            - name: dist
              mountPath: /code/dist
              readOnly: true
        - name: webpack-server
          image: registry.gitlab.com/kocherga/core/frontend
          command: ["./node_modules/.bin/webpack", "-w", "--config", "webpack.server.js"]
          env:
            - name: NODE_ENV
              value: development
          volumeMounts:
            - name: dist
              mountPath: /code/dist
      volumes:
        - name: dist
          emptyDir: {}
