# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kocherga.mastermind_dating.models.participant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_squash_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_telegram_uid', models.CharField(blank=True, max_length=100)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_invite_link', models.CharField(max_length=255)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='mastermind_dating.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=kocherga.mastermind_dating.models.participant.photo_path)),
                ('state', models.TextField(blank=True)),
                ('voted_for', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
                ('invite_email_sent', models.BooleanField(default=False)),
                ('telegram_uid', models.CharField(blank=True, max_length=100)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mastermind_dating.cohort')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='mastermind_dating.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastermind_dating_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.IntegerField()),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.participant')),
                ('whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.participant')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_uid', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mastermind_dating_telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
