# Generated by Django 2.1.7 on 2019-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0002_auto_20190223_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_uid',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
