# Generated by Django 2.2 on 2019-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0009_user_multiple_cohorts_p1'),
    ]

    operations = [
        migrations.RemoveField(model_name='user', name='cohort',),
        migrations.AlterField(
            model_name='user',
            name='cohorts',
            field=models.ManyToManyField(
                related_name='users', to='mastermind_dating.Cohort'
            ),
        ),
    ]
