# Generated by Django 2.2 on 2019-07-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0011_user_invite_email_sent'),
    ]

    operations = [
        migrations.RemoveField(model_name='cohort', name='sent_emails',),
    ]
