# Generated by Django 2.2 on 2019-07-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0012_no_sent_email_in_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='leader_telegram_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='cohort',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='groups',
                to='mastermind_dating.Cohort',
            ),
        ),
    ]
