# Generated by Django 2.2 on 2019-07-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kocherga.mastermind_dating.models.participant


def fill_participants(apps, schema_editor):
    User = apps.get_model('mastermind_dating', 'User')
    Participant = apps.get_model('mastermind_dating', 'Participant')

    for user in User.objects.all():
        if not user.cohorts.count():
            # skip - no cohorts
            continue

        Participant.objects.create(
            user=user.user,
            telegram_uid=user.telegram_uid,
            name=user.name,
            desc=user.desc,
            photo=user.photo,
            state=user.state,
            chat_id=user.chat_id,
            voted_for=user.voted_for,
            present=user.present,
            invite_email_sent=user.invite_email_sent,
            cohort=user.cohorts.first(),
            group=user.group,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mastermind_dating', '0013_cohort_groups_with_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_uid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=kocherga.mastermind_dating.models.participant.photo_path)),
                ('state', models.TextField(blank=True)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('voted_for', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
                ('invite_email_sent', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mastermind_dating.Cohort')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='mastermind_dating.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            fill_participants
        )
    ]
