# Generated by Django 2.2 on 2019-07-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0014_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='who_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.Participant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='whom_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.Participant'),
        ),
    ]
