# Generated by Django 2.2 on 2019-07-28 18:04

from django.db import migrations


def fill_participant_votes(apps, schema_editor):
    Vote = apps.get_model('mastermind_dating', 'Vote')
    Participant = apps.get_model('mastermind_dating', 'Participant')

    for vote in Vote.objects.all():
        vote.who_p = Participant.objects.get(user=vote.who.user)
        vote.whom_p = Participant.objects.get(user=vote.whom.user)
        vote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0015_vote_participant_p1'),
    ]

    operations = [migrations.RunPython(fill_participant_votes, lambda *args: None)]
