# Generated by Django 2.2 on 2019-07-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0017_vote_participant_p3'),
    ]

    operations = [
        migrations.RenameField(model_name='vote', old_name='who_p', new_name='who',),
        migrations.RenameField(model_name='vote', old_name='whom_p', new_name='whom',),
    ]
