# Generated by Django 2.2 on 2019-07-28 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mastermind_dating', '0019_telegram_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant', unique_together={('user', 'cohort')},
        ),
    ]
