# Generated by Django 2.2.5 on 2019-10-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0024_event_pk_p3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='event_google_id',
        ),
    ]
