# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('cookies', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_id', models.BigIntegerField(db_index=True, verbose_name='Номер карты')),
                ('start_ts', models.IntegerField(db_index=True)),
                ('end_ts', models.IntegerField(db_index=True)),
                ('imported_ts', models.IntegerField()),
                ('log_imported_ts', models.IntegerField(null=True)),
                ('people', models.IntegerField()),
                ('visit_length', models.IntegerField()),
                ('full_visit_length', models.IntegerField()),
                ('order_value', models.IntegerField()),
                ('time_value', models.IntegerField()),
                ('stuff_value', models.IntegerField()),
                ('payment_type', models.CharField(max_length=20)),
                ('is_fixed', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('tariff_time', models.CharField(max_length=20)),
                ('tariff_plan', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=1024)),
                ('history', models.TextField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'cm_orders',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.BigIntegerField()),
                ('ts', models.IntegerField()),
                ('order_value', models.IntegerField()),
                ('payment_type', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'db_table': 'cm_subscription_orders',
                'unique_together': {('card_id', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_id', models.BigIntegerField(db_index=True, verbose_name='Номер карты')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gender', models.CharField(blank=True, choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], max_length=20, verbose_name='Пол')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('time_discount', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('subscription_until', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('phone_number2', models.CharField(blank=True, max_length=40)),
                ('vk_link', models.CharField(blank=True, max_length=1024)),
                ('fb_link', models.CharField(blank=True, max_length=1024)),
                ('twitter_link', models.CharField(blank=True, max_length=1024)),
                ('instagram_link', models.CharField(blank=True, max_length=1024)),
                ('skype_link', models.CharField(blank=True, max_length=1024)),
                ('website_link', models.CharField(blank=True, max_length=1024)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('ref', models.CharField(blank=True, max_length=1024)),
                ('ref2', models.CharField(blank=True, max_length=1024)),
                ('mailing_list', models.BooleanField()),
                ('goods_discount', models.IntegerField()),
                ('activity_started', models.DateTimeField(blank=True, null=True)),
                ('activity_ended', models.DateTimeField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('total_spent', models.IntegerField()),
                ('privacy_mode', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=40, verbose_name='Приватность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'cm_customers',
            },
        ),
        migrations.CreateModel(
            name='OrderLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.IntegerField()),
                ('operation', models.CharField(max_length=1024)),
                ('ts', models.IntegerField(db_index=True)),
                ('login', models.CharField(max_length=80)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cm.order')),
            ],
            options={
                'db_table': 'cm_order_log',
                'unique_together': {('order', 'operation_id')},
            },
        ),
    ]
