# Generated by Django 2.1.5 on 2019-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
