# Generated by Django 2.1.5 on 2019-01-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlogentry',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='log_entries',
                to='cm.Order',
            ),
        ),
    ]
