# Generated by Django 2.1.5 on 2019-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0008_auto_20190210_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer', name='comment', field=models.TextField(blank=True),
        ),
    ]
