# Generated by Django 2.1.7 on 2019-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0009_auto_20190210_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('cookies', models.CharField(max_length=4096)),
            ],
        ),
    ]
