apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-django
spec:
  ports:
  - name: web
    port: 80
  selector:
    app: {{ .Release.Name }}-django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-django
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django
    spec:
      containers:
        - name: default
          image: {{ .Values.image.backend }}
{{- if .Values.dev }}
          command: ["./manage.py", "runserver", "0.0.0.0:80"]
{{- end }}
          ports:
            - containerPort: 80
{{- if not .Values.dev }}
          readinessProbe:
            httpGet:
              path: /api/graphql
              httpHeaders:
                - name: Host
                  value: localhost
              port: 80
            timeoutSeconds: 3
            periodSeconds: 10
{{- end }}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "2048Mi"
          volumeMounts:
{{ include "core.backend_mount_configs" . | indent 12 }}
          envFrom:
{{ include "core.backend_env_from" . | indent 12 }}
          env:
{{ include "core.backend_env_db" . | indent 12 }}
            - name: prometheus_multiproc_dir
              value: /tmp # TODO - create empty tmpfs dir to avoid file name collisions etc.
{{- if .Values.dev }}
            - name: PYTHONUNBUFFERED
              value: "0"  # fix runserver output on compilation issues
            - name: DJANGO_WATCHMAN_TIMEOUT
              value: "60"
{{- end }}
      volumes:
{{ include "core.backend_volumes" . | indent 8 }}

{{- if .Values.monitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-django
  namespace: monitor
spec:
  jobLabel: {{ .Release.Name }}-django
  selector:
    matchLabels:
      app: {{ .Release.Name }}-django
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: web
    path: /api/prometheus/metrics
    interval: 30s
{{- end }}
