apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chrome
spec:
  ports:
  - port: 9222
  selector:
    app: {{ .Release.Name }}-chrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chrome
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-chrome
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-chrome
    spec:
      containers:
      - name: default
        imagePullPolicy: Always
        image: {{ .Values.image.chrome }}
        ports:
          - containerPort: 9222
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "1024Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]  # FIXME - find a different chrome image which doesn't require this
