apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  KOCHERGA_WEBSITE: {{ .Values.env.common.KOCHERGA_WEBSITE | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data: {} # configured with https://nextjs.org/docs/basic-features/environment-variables since we need the same env on build
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  # not used much yet; will be used later when we move from main.py settings to env settings
  STATIC_S3_BUCKET: {{ .Values.env.backend.STATIC_S3_BUCKET | quote }}
  CDN_DOMAIN: {{ .Values.cdn_domain | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  main.py: {{ required "config.main_py is required" .Values.config.main_py | quote }}
