apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  STATIC_S3_BUCKET: {{ .Values.env.common.STATIC_S3_BUCKET | quote }}
  KOCHERGA_WEBSITE: {{ .Values.env.common.KOCHERGA_WEBSITE | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: {{ .Values.env.frontend.GOOGLE_ANALYTICS_ID | quote }}
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID: {{ .Values.env.frontend.FACEBOOK_PIXEL_ID | quote }}
  NEXT_PUBLIC_YANDEX_METRIKA_ID: {{ .Values.env.frontend.YANDEX_METRIKA_ID | quote }}
  NEXT_PUBLIC_VK_RETARGETING_ID: {{ .Values.env.frontend.VK_RETARGETING_ID | quote }}
  NEXT_PUBLIC_SENTRY_DSN_FRONTEND: {{ .Values.env.frontend.SENTRY_DSN_FRONTEND | quote }}
  NEXT_PUBLIC_VK_MESSAGES_WIDGET_ID: {{ .Values.env.frontend.VK_MESSAGES_WIDGET_ID | quote }}
  NEXT_PUBLIC_GOOGLE_MAPS_KEY: {{ .Values.env.frontend.GOOGLE_MAPS_KEY | quote }}
  NEXT_PUBLIC_STATIC_S3_BUCKET: {{ .Values.env.common.STATIC_S3_BUCKET | quote }}
  NEXT_PUBLIC_KOCHERGA_WEBSITE: {{ .Values.env.common.KOCHERGA_WEBSITE | quote }}
  SENTRY_AUTH_TOKEN: {{ .Values.sentry.auth_token | quote }}
  SENTRY_ORG: {{ .Values.sentry.org | quote }}
  SENTRY_PROJECT: {{ .Values.sentry.projects.frontend | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-env
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data: {} # not used yet; will be used later when we move from main.py settings to env settings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  main.py: {{ required "config.main_py is required" .Values.config.main_py | quote }}
