apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-importer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-importer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-importer
    spec:
      containers:
        - name: default
          image: {{ .Values.image.backend | quote }}
          command: ["./scripts/importer.py"]
          ports:
            - containerPort: 8000 # for prometheus metrics
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1024Mi"
              cpu: "0.5"
          volumeMounts:
{{ include "core.backend_mount_configs" . | indent 12 }}
          envFrom:
{{ include "core.backend_env_from" . | indent 12 }}
          env:
{{ include "core.backend_env_db" . | indent 12 }}
            - name: NO_DJANGO_PROMETHEUS
              value: "1"
      volumes:
{{ include "core.backend_volumes" . | indent 8 }}

{{- if .Values.monitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-importer
  namespace: monitor
spec:
  jobLabel: {{ .Release.Name }}-importer
  selector:
    matchLabels:
      app: {{ .Release.Name }}-importer
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: web
    interval: 30s
{{- end }}
