apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-django-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      # initContainers via https://stackoverflow.com/a/50838829
      # avoid starting the migrations before the mysql DB is online (especially probable in dev)
      initContainers:
        - name: wait-for-mysql
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 core-mysql 3306 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: default
          command: ["./scripts/upgrade.sh"]
          image: {{ .Values.image.backend | quote }}
          volumeMounts:
{{ include "core.backend_mount_configs" . | indent 12 }}
          envFrom:
{{ include "core.backend_env_from" . | indent 12 }}
          env:
{{ include "core.backend_env_db" . | indent 12 }}
      volumes:
{{ include "core.backend_volumes" . | indent 8 }}
      restartPolicy: Never
  backoffLimit: 2
