apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  ports:
  - port: 6379
  selector:
    app: {{ .Release.Name }}-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: redis:5.0
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "4Mi"
            limits:
              memory: "1024Mi"
