apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root_password: {{ required "root_password must be set" .Values.database.root_password | b64enc | quote }}
  password: {{ required "password must be set" .Values.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secrets.py: |-
    {{ required "config.secrets_py is required" .Values.config.secrets_py | b64enc }}
  KKMServer.pem: |-
    {{ .Values.config.KKMServer_pem | b64enc }}
{{- if .Values.backup.s3_bucket }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  S3_BACKUP_BUCKET: {{ .Values.backup.s3_bucket | b64enc | quote }}
  S3_PATH: {{ required "s3_path must be set for backups" .Values.backup.s3_path | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ required "aws_access_key must be set for backups" .Values.backup.aws_access_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "aws_secret_key must be set for backups" .Values.backup.aws_secret_key | b64enc | quote }}
{{- end }}
