apiVersion: v1
kind: Service
metadata:
  name: kocherga-chrome
spec:
  ports:
  - port: 9222
  selector:
    app: kocherga-chrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocherga-chrome
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: kocherga-chrome
  template:
    metadata:
      labels:
        app: kocherga-chrome
    spec:
      containers:
      - name: default
        imagePullPolicy: Always
        image: registry.gitlab.com/kocherga/core/chrome
        ports:
          - containerPort: 9222
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "1024Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]  # FIXME - find a different chrome image which doesn't require this
