# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kocherga_wagtail', '0001_squash_2021'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('active_description', wagtail.core.fields.RichTextField(blank=True, verbose_name='Описание активных проектов')),
            ],
            options={
                'abstract': False,
            },
            bases=('kocherga_wagtail.kochergapage',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(verbose_name='Короткое описание')),
                ('activity_summary', models.TextField(blank=True, null=True, verbose_name='Периодичность')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kocherga_wagtail.customimage')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('kocherga_wagtail.kochergapage',),
        ),
    ]
