# Generated by Django 2.2.5 on 2019-09-20 21:04

from django.db import migrations, models
import django.db.models.deletion
import kocherga.wagtail.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('projects', '0006_projectpage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(kocherga.wagtail.mixins.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
