# Generated by Django 3.0.5 on 2020-09-18 21:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_custom_wagtail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='active_description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Описание активных проектов'),
        ),
    ]
