# Generated by Django 3.1.3 on 2020-12-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_more_permissions'),
        ('django', '0002_more_collection_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='community_org_team_telegram_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='telegram.chat'),
        ),
    ]
