# Generated by Django 2.2.5 on 2019-10-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('interests', models.ManyToManyField(to='email.MailchimpInterest')),
            ],
        ),
    ]
