# Generated by Django 2.1.5 on 2019-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='shift',
            field=models.CharField(choices=[('MORNING_V1', 'MORNING_V1'), ('EVENING_V1', 'EVENING_V1'), ('MORNING', 'MORNING'), ('MIDDAY', 'MIDDAY'), ('EVENING', 'EVENING'), ('NIGHT', 'NIGHT')], max_length=20),
        ),
    ]
