# Generated by Django 2.1.7 on 2019-03-30 21:09

from django.db import migrations, models
import django.db.models.deletion


def fill_watchman(apps, schema_editor):
    Shift = apps.get_model('watchmen', 'Shift')
    Member = apps.get_model('staff', 'Member')
    for shift in Shift.objects.all():
        if shift.watchman_name == 'Ночь':
            shift.is_night = True
        else:
            shift.watchman = Member.objects.get(short_name=shift.watchman_name)

        shift.full_clean()
        shift.save()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_member_color'),
        ('watchmen', '0005_auto_20190331_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='watchman',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='staff.Member'
            ),
        ),
        migrations.RunPython(fill_watchman),
    ]
