# Generated by Django 2.2 on 2019-08-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen', '0012_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
