# Generated by Django 2.2.5 on 2020-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TildaPage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('content', models.FileField(upload_to='tilda/')),
            ],
        ),
    ]
