# Generated by Django 3.0.5 on 2020-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0004_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tildapage',
            name='show_header_and_footer',
            field=models.BooleanField(default=True),
        ),
    ]
