# Generated by Django 3.0.5 on 2020-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0005_show_header_and_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tildapage',
            name='page_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='body',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='content',
            field=models.FileField(editable=False, upload_to='tilda/'),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='path',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='title',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
    ]
