# Generated by Django 3.0.5 on 2020-07-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0006_page_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tildapage',
            name='content',
        ),
    ]
