# Generated by Django 3.0.5 on 2020-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0007_no_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tildapage',
            name='description',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
    ]
