# Generated by Django 3.0.10 on 2020-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0009_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tildapage',
            name='imported_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
