# Generated by Django 3.2.4 on 2021-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'Добрый мем',
                'verbose_name_plural': 'Добрые мемы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Название')),
                ('text', models.TextField(blank=True, max_length=1024, verbose_name='Текст')),
                ('channel', models.CharField(default='space_bot', max_length=40, verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('period', models.IntegerField(default=1, help_text='Повторять каждые N недель', verbose_name='Частота')),
                ('task', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='watchmen_routine.task')),
            ],
            options={
                'verbose_name': 'Расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
