# Generated by Django 2.1.5 on 2019-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task', name='name', field=models.TextField(max_length=1024),
        ),
    ]
