# Generated by Django 2.1.5 on 2019-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0002_auto_20190115_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('image', models.URLField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='schedule', old_name='routine', new_name='task',
        ),
    ]
