# Generated by Django 2.2 on 2019-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0006_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.IntegerField(
                default=1, help_text='Повторять каждые N недель', verbose_name='Частота'
            ),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='task',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedules',
                to='watchmen_routine.Task',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Текст'),
        ),
    ]
