# Generated by Django 2.2 on 2019-05-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0007_task_title'),
    ]

    operations = [
        migrations.RenameField(model_name='task', old_name='name', new_name='text',),
    ]
