# Generated by Django 2.2 on 2019-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmen_routine', '0008_task_text_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='channel',
            field=models.CharField(default='space_bot', max_length=40, verbose_name='Канал'),
        ),
    ]
