apiVersion: v1
kind: Service
metadata:
  name: kocherga-ludwig
spec:
  ports:
  - port: 80
  selector:
    app: kocherga-ludwig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocherga-ludwig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kocherga-ludwig
  template:
    metadata:
      labels:
        app: kocherga-ludwig
    spec:
      containers:
        - name: default
          imagePullPolicy: Always
          image: registry.gitlab.com/kocherga/core/backend
          command: ["./scripts/ludwig.py"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: "/code/kocherga/django/settings/secrets.py"
              subPath: "secrets.py"
              readOnly: true
            - name: configs
              mountPath: "/code/kocherga/django/settings/main.py"
              subPath: "main.py"
              readOnly: true
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kocherga.django.settings.main
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kocherga
                  key: db_password
      volumes:
        - name: secrets
          secret:
            secretName: kocherga
        - name: configs
          configMap:
            name: kocherga
