# Generated by Django 2.1.7 on 2019-02-17 11:26

from django.db import migrations, models
import django.db.models.deletion

def fill_prototype_link(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        if event.prototype_id:
            event.prototype_link_id = event.prototype_id
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prototype_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_events', to='events.EventPrototype'),
        ),
        migrations.RunPython(fill_prototype_link),
    ]
