# Generated by Django 2.1.7 on 2019-02-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_prototype_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='prototype_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='prototype_link',
            new_name='prototype',
        ),
    ]
