# Generated by Django 2.2 on 2019-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_dt_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='asked_for_visitors_ts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_ts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_ts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_ts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_ts',
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
