# Generated by Django 2.2.5 on 2019-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_master_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprototype',
            name='canceled_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventprototype',
            name='image',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
