# Generated by Django 2.2.5 on 2019-10-20 22:24

from django.db import migrations, models
import kocherga.events.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_pk_p6'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.SlugField(default=kocherga.events.models.event.generate_uuid),
        ),
    ]
