# Generated by Django 2.2.5 on 2019-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_ticket_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='day_before_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
