# Generated by Django 2.2.5 on 2019-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_rename_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='from_timepad',
            field=models.BooleanField(default=False),
        ),
    ]
