# Generated by Django 2.2.5 on 2019-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы',},
        ),
    ]
