# Generated by Django 2.2 on 2019-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0010_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
