prometheus:
  prometheusSpec:
    image:
      tag: v2.19.2
    externalUrl: https://prometheus.team.kocherga.club
    retentionSize: "16GB"
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    externalUrl: https://alertmanager.team.kocherga.club
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: "SECRET" # defined in secrets/prometheus.yaml file
    route:
      group_by: ["job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - match:
            alertname: Watchdog
          receiver: "null"
        - match:
          receiver: "slack"
          continue: true
    receivers:
      - name: "null"
      - name: "slack"
        slack_configs:
          - channel: "#infra_alerts"
            send_resolved: true
            # via: https://gist.github.com/l13t/d432b63641b6972b1f58d7c037eec88f
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}

grafana:
  image:
    tag: 7.1.1
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: hcloud-volumes # necessary to avoid "cannot patch" helm error
  plugins:
    - grafana-piechart-panel

# disable components which are not useful in k3s
# via https://github.com/rancher/k3s/issues/425
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
