# Generated by Django 2.1.7 on 2019-02-23 17:48

from django.db import migrations, models
import kocherga.mastermind_dating.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=kocherga.mastermind_dating.models.user.photo_path),
        ),
    ]
