# Generated by Django 2.1.7 on 2019-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0004_cohort_sent_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
