# Generated by Django 2.1.7 on 2019-02-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0006_user_voted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.User'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mastermind_dating.User'),
        ),
    ]
