# Generated by Django 2.2.5 on 2019-10-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind_dating', '0021_populate_telegram_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='event_google_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
