version: '3.4'

x-backend-environment: &backend-environment
  DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'
  DB_NAME: 'kocherga'
  DB_USER: 'root'
  DB_PASSWORD: ''
  prometheus_multiproc_dir: /tmp # TODO - create empty tmpfs dir to avoid file name collisions etc.
  DJANGO_WATCHMAN_TIMEOUT: 60

x-frontend-environment: &frontend-environment
  NODE_ENV: 'development'

x-backend:
  &backend
  image: registry.gitlab.com/kocherga/core/backend:dev
  volumes:
    - ../backend/kocherga:/code/kocherga
    - ../backend/tests:/code/tests
    - ../backend/data/volume:/data
  environment:
    <<: *backend-environment
  cap_add:
    - SYS_PTRACE

services:
  tgbot:
    <<: *backend
    command: ./scripts/tgbot.py
    depends_on:
      - db
