version: '3.4'

x-backend:
  &backend
  image: registry.gitlab.com/kocherga/core/backend:dev
  volumes:
    - code-py:/code/kocherga:nocopy
    - code-pytest:/code/tests:nocopy
    - data:/data:nocopy
  environment:
    PYTHONUNBUFFERED: '0'  # fix runserver output on compilation issues
    DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.dev'
    prometheus_multiproc_dir: /tmp # TODO - create empty tmpfs dir to avoid file name collisions etc.
    DJANGO_WATCHMAN_TIMEOUT: 60
  cap_add:
    - SYS_PTRACE

