version: '3.4'

x-backend:
  &backend
  image: registry.gitlab.com/kocherga/core/backend:${TAG}
  environment:
    DJANGO_SETTINGS_MODULE: 'kocherga.django.settings.ci'
    DB_NAME: 'kocherga'
    DB_USER: 'root'
    DB_PASSWORD: ''
  cap_add:
    - SYS_PTRACE

x-frontend:
  &frontend
  image: registry.gitlab.com/kocherga/core/frontend:${TAG}
  volumes:
    - ../backend/data:/data
  environment:
    NODE_ENV: 'production'
  cap_add:
    - SYS_PTRACE

services:
  api:
    << : *backend
    command: ./manage.py runserver --noreload 0.0.0.0:80
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - db
      - render-server
      - chrome
      - redis

  render-server:
    << : *frontend
    command: node ./dist/index.js
